Repository umccr/orcabus, pull requests merged in 2023-06, with the labels that each got.

#24 Init CDK-Pipeline
  .eslintrc.json
  Makefile
  bin/orcabus.ts
  bin/pipeline.ts
  cdk.json
  config/constants.ts
  lib/pipeline/orcabus-pipeline-stack.ts
  lib/workload/stateful/database/component.ts
  package.json
  test/workload/stateful/databaseConstruct.test.ts
  test/workload/stateful/eventbusConstruct.test.ts
  test/workload/stateful/schemaRegistryConstruct.test.ts
  test/workload/stateful/securityGroupConstruct.test.ts
  tsconfig.json
  yarn.lock
Labels: feature, cicd, devops

#25 Updated pipeline to use UMCCR AWS accounts
  Makefile
  README.md
  bin/orcabus.ts
  bin/pipeline.ts
  config/constants.ts
  lib/pipeline/orcabus-pipeline-stack.ts
  package.json
Labels: documentation, cicd, devops

#26 Improved Django template skel profile
  docs/developer/DJANGO_API.md
  docs/developer/DJANGO_PROC.md
  skel/django-api/src/project_name/models/base.py
  skel/django-api/src/project_name/models/helloworld.py
  skel/django-api/src/project_name/settings/base.py
  skel/django-api/src/project_name/tests/test_base.py
  skel/django-api/src/requirements.txt
  skel/django-proc/src/project_name/settings/base.py
  skel/django-proc/src/requirements.txt
Labels: feature

#29 Updated SequenceRunStateChange Event schema with proper envelope
  config/event_schemas/SequenceRunStateChange.json
Labels: feature, change request

#28 Implemented Sequence Run Manager microservice app
  .github/workflows/prbuild.yml
  Makefile
  config/event_schemas/SequenceRunStateChange.json
  docs/developer/SRM.md
  lib/workload/stateless/sequence_run_manager/component.ts
  lib/workload/stateless/sequence_run_manager/src/api.py
  lib/workload/stateless/sequence_run_manager/src/manage.py
  lib/workload/stateless/sequence_run_manager/src/migrate.py
  lib/workload/stateless/sequence_run_manager/src/requirements.txt
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/fields.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/commands/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/commands/generate_mock_data.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/migrations/0001_initial.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/migrations/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/models/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/models/base.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/models/sequence.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/pagination.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/renderers.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/routers.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/serializers.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/settings/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/settings/aws.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/settings/base.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/settings/it.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/settings/local.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/tests/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/tests/factories.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/tests/test_base.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/tests/test_models.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/tests/test_viewsets.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/urls/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/urls/base.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/urls/local.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/viewsets/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/viewsets/sequence.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/wsgi.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequence.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/lambdas/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/lambdas/bssh_event.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/services/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/services/sequence_srv.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/case.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/test_bssh_event.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/test_sequence_srv.py
Labels: feature

#27 FileManager microservice Rust skel
  .gitignore
  docker-compose.yml
  docs/developer/RUST_API.md
  openapi/README.md
  openapi/ica/v1/README.md
  openapi/ica/v1/console.json
  openapi/ica/v1/ens.json
  openapi/ica/v1/gds.json
  openapi/ica/v1/tes.json
  openapi/ica/v1/wes.json
  openapi/ica/v2/README.md
  openapi/ica/v2/openapi_public.yaml
  openapi/orcabus/filemanager.json
  skel/rust-api/.gitignore
  skel/rust-api/Cargo.lock
  skel/rust-api/Cargo.toml
  skel/rust-api/README.md
  skel/rust-api/build.rs
  skel/rust-api/src/db.rs
  skel/rust-api/src/file.rs
  skel/rust-api/src/lib.rs
  skel/rust-api/src/main.rs
Labels: feature

#30 Improved SequenceRunStateChange Event schema
  config/event_schemas/SequenceRunStateChange.json
  docs/developer/SRM.md
Labels: change request

#31 Improved Django Skel by removing base setting as default
  skel/django-api/src/migrate.py
  skel/django-api/src/project_name/wsgi.py
  skel/django-api/src/project_name_proc/lambdas/hello_proc.py
  skel/django-proc/src/migrate.py
  skel/django-proc/src/project_name_proc/lambdas/hello_proc.py
Labels: change request

#34 Improved GHA CI container image caching with composite action
  .github/actions/cache-image/action.yml
  .github/workflows/caches.yml
  .github/workflows/prbuild.yml
Labels: cicd, refactor

#32 Improved GHA CI build and local dev DX
  .github/actions/cache-image/action.yml
  .github/workflows/prbuild.yml
  README.md
  docker-compose.ci.yml
  docker-compose.yml
  requirements-test.txt
  skel/rust-api/.env.example
Labels: documentation, cicd

#36 Implemented Sequence Run Manager BSSH event processing
  docs/developer/SRM.md
  lib/workload/stateless/sequence_run_manager/src/migrate.py
  lib/workload/stateless/sequence_run_manager/src/requirements.txt
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/commands/generate_mock_bssh_event.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/management/commands/generate_mock_domain_event.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager/wsgi.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequence.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/AWSEvent.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/SequenceRunStateChange.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/__init__.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/domain/sequencerunstatechange/marshaller.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/lambdas/bssh_event.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/case.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/test_bssh_event.py
  lib/workload/stateless/sequence_run_manager/src/sequence_run_manager_proc/tests/test_sequence_domain.py
Labels: feature
