Repository umccr/orcabus, pull requests merged in 2024-07, with the labels that each got.

#383 Fix: STG Deployment
  cdk.context.json
  lib/pipeline/statefulPipelineStack.ts
  lib/workload/components/api-gateway/index.ts
Labels: fix

#372 feat: basic filemanager query API
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_entities.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/lib.rs
  lib/workload/stateless/stacks/filemanager/filemanager-http-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-ingest-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-inventory-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/migration.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/lib.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
Labels: feature, filemanager

#385 fix(filemanager): avoid using to_url_lossy when loading database credentials
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
Labels: fix, filemanager

#386 Feat: Deploy Stateless to Gamma
  lib/pipeline/statelessPipelineStack.ts
Labels: platform

#387 Fixed WorkflowManager event rule syntax
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
Labels: fix

#388 feat: deploy filemanager API and add OpenAPI docs
  .prettierignore
  .secrets.baseline
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/query.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-build/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_entities.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/lib.rs
  lib/workload/stateless/stacks/filemanager/filemanager-http-lambda/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-http-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-ingest-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-inventory-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/filemanager/build.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/csv_inventory_manifest.checksum
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/csv_inventory_manifest.json
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/csv_inventory_no_version_manifest.checksum
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/csv_inventory_no_version_manifest.json
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/orc_inventory_manifest.checksum
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/orc_inventory_manifest.json
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/parquet_inventory_manifest.checksum
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/parquet_inventory_manifest.json
Labels: feature, filemanager

#392 feat: filemanager pagination
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
Labels: feature, filemanager

#396 fix(filemanager): sequencer ordering
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/database/migrations/0003_add_sequencer_index.sql
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
Labels: fix, filemanager

#399 fix: filemanager e_tag quoting
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
Labels: fix, filemanager

#400 Fixed ICAv2 JWT secret name production
  config/constants.ts
Labels: bug, fix

#409 feat: filemanager filter query parameters
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filtering.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
Labels: feature, filemanager

#411 Feat(metadata-manager): Schema Change
  config/config.ts
  config/stacks/dataBucket.ts
  lib/workload/stateful/stacks/data/README.md
  lib/workload/stateful/stacks/data/stack.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/metadata-manager/.gitignore
  lib/workload/stateless/stacks/metadata-manager/Makefile
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/trigger_sync_handler.py
  lib/workload/stateless/stacks/metadata-manager/app/migrations/0003_remove_specimen_subjects_historicalspecimen_subject_and_more.py
  lib/workload/stateless/stacks/metadata-manager/app/models/lab/specimen.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/test_models.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/utils.py
  lib/workload/stateless/stacks/metadata-manager/docs/schema.drawio.svg
  lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py
Labels: change request

#415 feat: filemanager current state
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
Labels: feature, filemanager

#416 Feature(metadata-manager): Additional API
  lib/workload/stateless/stacks/metadata-manager/app/models/base.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/test_viewsets.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
Labels: feature

#419 Fix (MM): Dependency Issue
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
Labels: fix

#418 feat(filemanager): add database mocking to local API server
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
Labels: feature, filemanager

#421 Feat(MM): Upgrade OpenAPI Version 3
  lib/workload/stateless/stacks/metadata-manager/Makefile
  lib/workload/stateless/stacks/metadata-manager/app/pagination.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/urls/local.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
Labels: feature

#424 feat(filemanager): attribute updating API
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-ingest-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-inventory-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager

#425 Feat: Running Microservice API Locally
  Makefile
  README.md
  compose.yml
  lib/workload/stateless/stacks/metadata-manager/Dockerfile
  lib/workload/stateless/stacks/metadata-manager/Makefile
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/app/settings/it.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/sequence-run-manager/.gitignore
  lib/workload/stateless/stacks/sequence-run-manager/Dockerfile
  lib/workload/stateless/stacks/sequence-run-manager/Makefile
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/it.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
  lib/workload/stateless/stacks/workflow-manager/.gitignore
  lib/workload/stateless/stacks/workflow-manager/Dockerfile
  lib/workload/stateless/stacks/workflow-manager/Makefile
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/it.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
  shared/init-db.sql
  shared/mock-db.yml
Labels: devops

#426 Chore: Upgrade OpenAPI3 for DRF Microservice
  Makefile
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/urls/local.py
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/pagination.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/local.py
  lib/workload/stateless/stacks/workflow-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/workflow-manager/deps/requirements.txt
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/pagination.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/local.py
Labels: fix, devops

#429 fix: add filemanager to local API setup
  Makefile
  README.md
  compose.yml
  lib/workload/stateless/stacks/filemanager/.dockerignore
  lib/workload/stateless/stacks/filemanager/.env.example
  lib/workload/stateless/stacks/filemanager/.gitignore
  lib/workload/stateless/stacks/filemanager/Dockerfile
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/filemanager/compose.yml
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
Labels: devops

#433 Fixed cttsov2 post-processing docker architecture ARM_64
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/stack.ts
Labels: fix
