Repository umccr/orcabus, pull requests merged in 2024-03, with the labels that each got.

#128 fix(postgres-manager): failing unit test from `cdk-nag`
  config/constants.ts
  lib/workload/orcabus-stateless-stack.ts
  lib/workload/stateless/postgres_manager/deploy/postgres-manager-stack.ts
  lib/workload/stateless/postgres_manager/function/alter-pg-db-owner.ts
  lib/workload/stateless/postgres_manager/function/create-pg-db.ts
  lib/workload/stateless/postgres_manager/function/create-pg-iam-role.ts
  lib/workload/stateless/postgres_manager/function/create-pg-login-role.ts
  lib/workload/stateless/postgres_manager/function/type.ts
  lib/workload/stateless/postgres_manager/function/utils.ts
  lib/workload/stateless/postgres_manager/package.json
  test/stateless/stateless-deployment.test.ts
  tsconfig.json
Labels: fix

#124 fix(filemanager): re-run sqlx prepare with all targets
  lib/workload/stateless/filemanager/.sqlx/query-3fe88592da137c9706a5b541ef8edb7a794c72051d12c8c3b57d853b37a8392e.json
  lib/workload/stateless/filemanager/.sqlx/query-63da484d18ed2571639cfddadf992fe9ea92767a8274859de371f4e954e554b8.json
  lib/workload/stateless/filemanager/Makefile
  lib/workload/stateless/filemanager/README.md
Labels: fix, filemanager

#130 codepipeline notication
  lib/pipeline/orcabus-stateful-pipeline-stack.ts
  lib/pipeline/orcabus-stateless-pipeline-stack.ts
Labels: feature

#136 fix(filemanager): ingest constraints
  lib/workload/stateless/filemanager/database/migrations/0002_add_s3_object_table.sql
  lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/filemanager/filemanager/src/handlers/aws.rs
Labels: fix, filemanager

#149 Postgres Manager Enhancement
  lib/workload/stateless/postgres_manager/README.md
  lib/workload/stateless/postgres_manager/function/create-pg-login-role.ts
Labels: fix

#151 Added sequence_run_manager database config
  config/constants.ts
Labels: feature, change request

#152 refactor: swap rust function
  lib/pipeline/orcabus-stateless-pipeline-stack.ts
  lib/workload/stateless/filemanager/.gitignore
  lib/workload/stateless/filemanager/.sqlx/query-3fe88592da137c9706a5b541ef8edb7a794c72051d12c8c3b57d853b37a8392e.json
  lib/workload/stateless/filemanager/.sqlx/query-63da484d18ed2571639cfddadf992fe9ea92767a8274859de371f4e954e554b8.json
  lib/workload/stateless/filemanager/.sqlx/query-7495c606d6e756a6e53e45fc0ee6a0765922a5fef3d512c719d4aec543d0d8a6.json
  lib/workload/stateless/filemanager/.sqlx/query-a21baafb9a67774ec404c4ef80ff43b6f0d78fd3a31ae2517ba889ed50496dff.json
  lib/workload/stateless/filemanager/.sqlx/query-b93388efd27ae9253929e157bc8df247af518d4fafe42761f1488d1927d616c6.json
  lib/workload/stateless/filemanager/.sqlx/query-bfa37a3a6325c7bf5449aba02be91338f4623a239c677301c9d13bcbd5e65e78.json
  lib/workload/stateless/filemanager/.sqlx/query-c05597a449cf3e2e125bec198486d2bc57b270abf737f64cfe386650fd1d2b9e.json
  lib/workload/stateless/filemanager/Makefile
  lib/workload/stateless/filemanager/README.md
  lib/workload/stateless/filemanager/deploy/README.md
  lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
  package.json
  yarn.lock
Labels: fix, filemanager

#154 fix(pipeline): install Rust for unit tests
  lib/pipeline/orcabus-stateless-pipeline-stack.ts
Labels: platform, fix

#156 fix: pipeline error caused by filemanager containerized build
  lib/pipeline/orcabus-stateless-pipeline-stack.ts
  lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
Labels: fix, pipeline

#155 Implemented SequenceRunManager app deployment
  config/constants.ts
  lib/workload/orcabus-stateful-stack.ts
  lib/workload/orcabus-stateless-stack.ts
  lib/workload/stateless/sequence_run_manager/Makefile
  lib/workload/stateless/sequence_run_manager/README.md
  lib/workload/stateless/sequence_run_manager/deploy/README.md
  lib/workload/stateless/sequence_run_manager/deploy/apigw/component.ts
  lib/workload/stateless/sequence_run_manager/deploy/component.ts
  lib/workload/stateless/sequence_run_manager/deps/requirements-dev.txt
  lib/workload/stateless/sequence_run_manager/deps/requirements-test.txt
  lib/workload/stateless/sequence_run_manager/deps/requirements.txt
  lib/workload/stateless/sequence_run_manager/sequence_run_manager/__init__.py
  lib/workload/stateless/sequence_run_manager/sequence_run_manager/settings/aws.py
  lib/workload/stateless/sequence_run_manager/sequence_run_manager_proc/lambdas/bssh_event.py
  package.json
  skel/django-api/component.ts
  test/stateful/stateful-deployment.test.ts
  test/stateless/stateless-deployment.test.ts
  yarn.lock
Labels: feature, change request

#163 Fixed SequenceRunManager architecture to ARM64
  lib/workload/stateless/sequence_run_manager/deploy/component.ts
Labels: fix

#157 Update Readme and Refactor Pipeline Code
  Makefile
  README.md
  bin/orcabus.ts
  cdk.json
  docs/developer/MICROSERVICE.md
  docs/developer/SHARED_RESOURCES.md
  lib/pipeline/orcabus-stateful-pipeline-stack.ts
  lib/pipeline/orcabus-stateless-pipeline-stack.ts
  package.json
  yarn.lock
Labels: documentation, pipeline

#171 Trimmed down the sequence_run_manager
  lib/workload/stateless/sequence_run_manager/compose.yml
  lib/workload/stateless/sequence_run_manager/deps/requirements-dev.txt
  lib/workload/stateless/sequence_run_manager/deps/requirements-test.txt
  lib/workload/stateless/sequence_run_manager/deps/requirements.txt
  lib/workload/stateless/sequence_run_manager/sequence_run_manager/settings/base.py
Labels: dependencies

#172 Fixed deployment by removing sequence_run_manager HttpStage
  lib/workload/stateless/sequence_run_manager/deploy/component.ts
Labels: fix

#173 build(deps): bump postgres versions to match RDS instance
  lib/workload/stateless/filemanager/database/Dockerfile
  shared/mock-db.yml
Labels: dependencies

#161 fix: filemanager uuids
  lib/workload/stateless/filemanager/Cargo.lock
  lib/workload/stateless/filemanager/filemanager/Cargo.lock
  lib/workload/stateless/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/filemanager/filemanager/src/lib.rs
  lib/workload/stateless/filemanager/filemanager/src/uuid.rs
Labels: fix, filemanager

#175 Improved sequence_run_manager API Gateway setup
  lib/workload/stateless/sequence_run_manager/api.py
  lib/workload/stateless/sequence_run_manager/deploy/apigw/component.ts
  lib/workload/stateless/sequence_run_manager/deploy/component.ts
  lib/workload/stateless/sequence_run_manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/sequence_run_manager/sequence_run_manager/urls/local.py
  skel/django-api/src/api.py
Labels: feature, fix

#181 Fixed sequence_run_manager endpoint unit test
  .gitignore
  lib/workload/stateless/sequence_run_manager/.coveragerc
  lib/workload/stateless/sequence_run_manager/Makefile
  lib/workload/stateless/sequence_run_manager/README.md
  lib/workload/stateless/sequence_run_manager/deps/requirements-dev.txt
  lib/workload/stateless/sequence_run_manager/deps/requirements-test.txt
  lib/workload/stateless/sequence_run_manager/sequence_run_manager/tests/test_viewsets.py
Labels: fix

#180 refactor: filemanager stack
  config/constants.ts
  lib/workload/components/cdk_resource_invoke.ts
  lib/workload/orcabus-stateless-stack.ts
  lib/workload/stateful/event_source/component.ts
  lib/workload/stateless/filemanager/Cargo.lock
  lib/workload/stateless/filemanager/Cargo.toml
  lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/filemanager/deploy/lib/filemanager.ts
  lib/workload/stateless/filemanager/filemanager-http-lambda/Cargo.toml
  lib/workload/stateless/filemanager/filemanager-ingest-lambda/Cargo.toml
  lib/workload/stateless/filemanager/filemanager-migrate-lambda/Cargo.toml
  lib/workload/stateless/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/filemanager/filemanager/src/env.rs
  test/stateless/cdkResourceInvoke.test.ts
  test/stateless/stateless-deployment.test.ts
Labels: refactor, filemanager

#183 fix(filemanager): let docker decide on container names
  lib/workload/stateless/filemanager/Makefile
  lib/workload/stateless/filemanager/compose.yml
Labels: fix, filemanager

#184 fix(filemanager): use docker run to get unique containers
  lib/workload/stateless/filemanager/.env.example
  lib/workload/stateless/filemanager/Makefile
  lib/workload/stateless/filemanager/compose.yml
  lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
Labels: fix, filemanager

#187 fix(filemanager): silence Makefile output and trim lines
  lib/workload/stateless/filemanager/Makefile
  lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
  package.json
  yarn.lock
Labels: fix, filemanager

#189 fix(filemanager): add uuid to target directory to avoid concurrency errors
  lib/workload/stateless/filemanager/Cargo.lock
  lib/workload/stateless/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/filemanager/filemanager-http-lambda/Cargo.toml
  lib/workload/stateless/filemanager/filemanager-ingest-lambda/Cargo.toml
  lib/workload/stateless/filemanager/filemanager-migrate-lambda/Cargo.toml
  lib/workload/stateless/filemanager/filemanager/Cargo.toml
Labels: fix, filemanager
