Repository umccr/orcabus, pull requests merged in 2024-12, with the labels that each got.

#740 Swap max items for max results
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
Labels: bug

#742 Max results can't be more than 100
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json
Labels: bug

#741 Update holmes glue wrappers to match new input syntax
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_4/launch-holmes-extract-event/step_functions_templates/cttsov2_complete_to_holmes_bam_extraction_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_6/launch-holmes-extract-event/step_functions_templates/holmes_extract_wrapper_sfn_template.asl.json
Labels: bug

#744 Bugfix, add extact arn to map step
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_6/launch-holmes-extract-event/step_functions_templates/holmes_extract_wrapper_sfn_template.asl.json
Labels: bug

#746 Fix map output size limit
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_ora_sfn_template.asl.json
Labels: bug

#747 Catch the Ecs Rate Exceeded exception
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_ora_sfn_template.asl.json
Labels: bug

#749 fix(data-migrate): fix stdout capture and failed step functions
  lib/workload/stateless/stacks/data-migrate/data_mover/cli.py
  lib/workload/stateless/stacks/data-migrate/data_mover/data_mover.py
  lib/workload/stateless/stacks/data-migrate/poetry.lock
  lib/workload/stateless/stacks/data-migrate/pyproject.toml
Labels: fix

#753 Feat(SRM) models refatcor
  docs/schemas/events/sequencerunmanager/SequenceRunStateChange.schema.json
  docs/schemas/events/sequencerunmanager/example/SRSC__started.json
  docs/schemas/events/sequencerunmanager/example/SRSC__succeeded.json
  lib/workload/stateless/stacks/sequence-run-manager/deploy/README.md
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/migrations/0001_initial.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/migrations/0002_alter_sequence_status.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/__init__.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/comment.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/state.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/__init__.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/comment.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/state.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/tests/test_viewsets.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/comment.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/state.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/AWSEvent.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/SequenceRunStateChange.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/bssh_event.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_state_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_bssh_event.py
Labels: feature

#754 fix(data-migrate): add structured output to step functions
  lib/workload/stateless/stacks/data-migrate/data_mover/cli.py
  lib/workload/stateless/stacks/data-migrate/data_mover/data_mover.py
  lib/workload/stateless/stacks/data-migrate/poetry.lock
Labels: platform, fix

#755 Fix(SRM) SRM api issue
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/migrations/0002_alter_sequence_run_folder_path.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/sequence.py
Labels: fix

#756 Fix/add delete for api allow methods
  lib/workload/components/api-gateway/index.ts
Labels: fix

#761 Add ora reference for tn workflows
  config/constants.ts
  config/stacks/tumorNormalPipelineManager.ts
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/deploy/index.ts
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/lambdas/add_ora_reference_py/add_ora_reference.py
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/step_functions_templates/set_tn_cwl_inputs_sfn.asl.json
Labels: feature, critical

#763 Add ora compression to cttsov2 workflow
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/docker-entrypoint.sh
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/stack.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/check_fastq_list_row_is_ora_py/check_fastq_list_row_is_ora.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/convert_ora_to_cache_uri_gz_path_py/convert_ora_to_cache_uri_gz_path.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json
Labels: feature, epic

#759 feat(htsget): add htsget support
  config/config.ts
  config/stacks/htsget.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/htsget/README.md
  lib/workload/stateless/stacks/htsget/deploy.toml
  lib/workload/stateless/stacks/htsget/stack.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
  package.json
  yarn.lock
Labels: feature, filemanager

#762 feat: filemanager multiple same-key queries
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-build/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager-ingest-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-inventory-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/prelude.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_object.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/sea_orm_active_enums.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
Labels: feature, filemanager

#767 Updated aurora automated backup retention
  config/stacks/shared.ts
  lib/workload/stateful/stacks/shared/constructs/database/index.ts
  test/stateful/pipeline/deployment.test.ts
Labels: change request

#769 Added readme for launching the tumor normal pipeline
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/Readme.md
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/docs/ready_data_schema.json
Labels: documentation

#768 Implemented OrcaBus database tier-2 backup retention
  config/stacks/shared.ts
  lib/workload/stateful/stacks/shared/constructs/database/index.ts
  test/stateful/pipeline/deployment.test.ts
  test/stateful/shared/databaseConstruct.test.ts
Labels: feature, platform

#771 build(fmannotator): update deps
  lib/workload/stateless/stacks/fmannotator/go.mod
  lib/workload/stateless/stacks/fmannotator/go.sum
Labels: dependencies, filemanager

#770 Feat(wfr) api add "DEPRECATED" state
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run_action.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_action.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py
Labels: feature

#777 Resolve division by zero error
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_sequali_stats/get_sequali_stats.py
Labels: fix

#783 fix(pg-dd): python version and environment variables
  lib/workload/stateless/stacks/pg-dd/.env.example
  lib/workload/stateless/stacks/pg-dd/Dockerfile
  lib/workload/stateless/stacks/pg-dd/deploy/stack.ts
  lib/workload/stateless/stacks/pg-dd/pg_dd/handler.py
  lib/workload/stateless/stacks/pg-dd/pg_dd/pg_dd.py
  lib/workload/stateless/stacks/pg-dd/poetry.lock
  lib/workload/stateless/stacks/pg-dd/pyproject.toml
Labels: platform, fix

#778 Remove null inputs from inputs payload
  lib/workload/stateless/stacks/transcriptome-pipeline-manager/step_functions_templates/set_wts_cwl_inputs_sfn.asl.json
Labels: fix, pipeline

#787 Fix step functions where next attribute for Merge Boolean Skipped new step
  lib/workload/stateless/stacks/transcriptome-pipeline-manager/step_functions_templates/set_wts_cwl_inputs_sfn.asl.json
Labels: bug, fix

#791 fix(filemanager): add permissions for analysis and fastq archive buckets
  config/stacks/fileManager.ts
  test/stateless/deployment.test.ts
Labels: fix, filemanager

#793 feat(filemanager): update ingest id
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager
