Repository umccr/orcabus, pull requests merged in 2024-10, with the labels that each got.

#582 Fix `orcabus_id` filter (w/ prefixes)
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/base.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/contact.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/individual.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/project.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/sample.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/subject.py
Labels: fix, metadata_manager

#583 Feat(MM): API Serializer Expansion
  lib/workload/stateless/stacks/metadata-manager/app/serializers/library.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/project.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/sample.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/project.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/sample.py
Labels: feature, metadata_manager

#588 Fix error when checking source uris have been transferred
  lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
  lib/workload/components/icav2-copy-files/index.ts
Labels: fix

#585 feat(filemanager): ingest_id tagging and object move tracking
  lib/workload/stateless/stacks/filemanager/database/migrations/0002_s3_ingest_id.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/docs/MOVED_OBJECTS.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_object.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
Labels: feature, filemanager

#587 fix(filemanager): version_id for S3 API calls
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
Labels: fix, filemanager

#590 Merge pull request #588 from umccr/hotfix/bssh-fastq-copy-quick-fix
  lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
  lib/workload/components/icav2-copy-files/index.ts
Labels: bug, fix

#594 Add RESOLVED state as supported WorkflowRun state
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
Labels: feature

#596 feat(filemanager): accept multiple keys in API
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
Labels: feature, filemanager

#598 Fix: Drop incomplete record before metadata processing
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/load_from_csv.py
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/trigger_sync_handler.py
  lib/workload/stateless/stacks/metadata-manager/deploy/README.md
  lib/workload/stateless/stacks/metadata-manager/handler/load_custom_metadata_csv.py
  lib/workload/stateless/stacks/metadata-manager/handler/sync_tracking_sheet.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/load_csv_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py
Labels: fix, metadata_manager

#601 feat(filemanager): docker caching and current state default
  compose.yml
  lib/workload/stateless/stacks/filemanager/Dockerfile
  lib/workload/stateless/stacks/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/compose.yml
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
  lib/workload/stateless/stacks/fmannotator/go.mod
  lib/workload/stateless/stacks/fmannotator/go.sum
  lib/workload/stateless/stacks/fmannotator/handlers.go
  lib/workload/stateless/stacks/fmannotator/handlers_test.go
  lib/workload/stateless/stacks/fmannotator/internal/test/test.go
Labels: devops, filemanager

#599 Feature/analysis journey
  lib/workload/stateless/stacks/workflow-manager/Makefile
  lib/workload/stateless/stacks/workflow-manager/deps/requirements.txt
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/fields.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/clean_db.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_analysis_for_metadata.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/migrations/0001_initial.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/migrations/0002_alter_state_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/analysis_context.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_context.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/factories.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/analysis_context.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/transition_bcm_fastq_copy.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_analysisruns_for_libraries.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/emit_workflow_run_state_change.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py
Labels: feature

#606 Feat (MM): History API for Models
  lib/workload/stateless/stacks/metadata-manager/Makefile
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/clean_db.py
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/insert_mock_data.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/contact.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/individual.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/library.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/project.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/sample.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/subject.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/test_models.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/utils.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/base.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/contact.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/individual.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/project.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/sample.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/subject.py
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-test.txt
Labels: feature, metadata_manager

#608 wfm update for ui fix
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
Labels: fix

#603 cttsov2 job checker requires permissions to list executions
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
Labels: bug

#602 Add fastqc / sequali stats to fastq list row events for first 1 million reads
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/clean_up_fastq_list_rows_py/clean_up_fastq_list_rows.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/generate_event_data_objects_py/generate_event_data_objects.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_demultiplex_stats_py/get_demultiplex_stats.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_demultiplex_stats_py/requirements.txt
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_fastqc_stats/Dockerfile
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_fastqc_stats/requirements.txt
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_fastqc_stats/run_fastqc.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_sequali_stats/Dockerfile
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_sequali_stats/get_sequali_stats.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/lambdas/get_sequali_stats/requirements.txt
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/step_functions_templates/fastq_list_row_event_shower_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts
Labels: bug, feature

#604 Pieriandx needs 'SUCCEEDED' status as positive terminal status not 'COMPLETE'
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/get_informaticsjob_and_report_status_py/get_informaticsjob_and_report_status.py
Labels: bug

#612 Handle orcabus_id with prefix when saving model objects
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_models.py
Labels: bug, fix

#615 feat: filemanager partitions
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/filemanager/database/migrations/0003_s3_current_state.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/reset_current_state.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/migrate.ts
  lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_object.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager

#616 fix(filemanager): resetting current state should include old verisons
  lib/workload/stateless/stacks/filemanager/database/migrations/0003_s3_current_state.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/reset_current_state.sql
  lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
Labels: fix, filemanager

#613 wfr/ feat-comments-resolved-status-mutation-module
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/migrations/0002_workflowruncomment.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run_comment.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_context.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run_comment.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/analysis_context.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_comment.py
Labels: feature

#617 Feat: Add Authoriser Based on User Pool Group
  config/config.ts
  config/constants.ts
  config/stacks/authorizationManager.ts
  lib/workload/components/api-gateway/README.md
  lib/workload/components/api-gateway/index.ts
  lib/workload/stateful/stacks/authorization-manager/README.md
  lib/workload/stateful/stacks/authorization-manager/cedarSchema.json
  lib/workload/stateful/stacks/authorization-manager/http-lambda-authorizer/admin_access_authorizer.py
  lib/workload/stateful/stacks/authorization-manager/stack.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  test/stateful/pipeline/deployment.test.ts
Labels: feature

#619 Remove unused stacky tables
  config/constants.ts
  config/stacks/stackyMcStackFace.ts
  lib/workload/stateful/stacks/stacky-mcstackface-dynamodb/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts
Labels: change request

#621 feat(event-source): ignore cache directories
  config/stacks/shared.ts
  lib/workload/stateful/stacks/shared/constructs/event-source/index.ts
  test/stateful/shared/eventSourceConstruct.test.ts
Labels: platform

#623 Updated json paths for portal run id and workflow run name
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/gorilla/part_1/bclconvert-interop-qc-draft-event-maker/step_functions_templates/generate_bclconvert_interop_qc_draft_event_sfn_template.asl.json
Labels: bug

#625 feat(event-source): add archive bucket as event source
  config/constants.ts
  config/stacks/shared.ts
Labels: platform

#626 Fix library lookup with prefixed orcabusId
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py
Labels: fix

#630 Fixed roket get-individual-id step
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/step_functions_templates/umccrise_and_wts_complete_to_rnasum_draft.asl.json
Labels: bug

#631 Retry lambdas with delay of 60 seconds
  lib/workload/components/icav2-copy-files-batch/step_functions_templates/copy_files_batch_sfn.asl.json
  lib/workload/components/icav2-copy-files/step_functions_templates/copy_files_sfn.asl.json
  lib/workload/components/sfn-generate-workflowrunstatechange-ready-event/step_functions_templates/generate_analysis_engine_parameters_from_ssm_sfn_template.asl.json
  lib/workload/components/sfn-icav2-ready-event-handler/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json
  lib/workload/components/sfn-nf-batch-ready-event-handler/step_functions_templates/launch_nextflow_pipeline_template.asl.json
  lib/workload/components/sfn-nf-batch-state-change-event-handler/step_functions_templates/capture_aws_batch_completion_events_template.asl.json
  lib/workload/components/sfn-workflowdraftrunstatechange-common-preamble/step_functions_templates/workflowdraftrunstatechange_preamble_template.asl.json
  lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/step_functions_templates/set_bclconvert_interop_qc_cwl_outputs_sfn.asl.json
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_outputs.asl.json
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/launch_pieriandx.asl.json
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/launch_pieriandx_case_creation.asl.json
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/launch_pieriandx_informaticsjob_creation.asl.json
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/launch_pieriandx_sequencerrun_creation.asl.json
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/monitor_runs.asl.json
  lib/workload/stateless/stacks/rnasum-pipeline-manager/step_functions_templates/set_rnasum_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/rnasum-pipeline-manager/step_functions_templates/set_rnasum_cwl_outputs_sfn.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_1/samplesheet-event-shower/step_functions_templates/samplesheet_event_shower_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/clag/part_2/fastq-list-rows-event-shower/step_functions_templates/fastq_list_row_event_shower_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/elmer/part_1/bclconvert-succeeded-to-bssh-fastq-copy/step_functions_templates/bclconvert_succeeded_to_bssh_fastq_copy_draft_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/step_functions_templates/library_wts_qc_complete_to_oncoanalyser_rna_ready_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/step_functions_templates/tn_complete_to_oncoanalyser_dna_ready_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_3/fastq-list-row-event-shower-complete-to-cttsov2-ready/step_functions_templates/fastq_list_row_shower_complete_event_to_cttsov2_draft_events_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_3/fastq-list-rows-shower-complete-to-wgts-qc/step_functions_templates/fastq_list_rows_shower_complete_to_wgts_qc_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_4/push-fastq-list-row-qc-complete-event/step_functions_templates/wgts_qc_complete_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_5/library-qc-complete-event/step_functions_templates/wgts_library_qc_complete_event_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_3/library-qc-complete-db-to-tn-ready/step_functions_templates/add_library_qc_complete_to_tn_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_3/library-qc-complete-to-wts/step_functions_templates/add_library_qc_complete_to_wts_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/step_functions_templates/cttso_v2_outputs_to_pieriandx_ready_event_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/tn-complete-to-umccrise-draft/step_functions_templates/tn_complete_to_umccrise_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/step_functions_templates/umccrise_and_wts_complete_to_rnasum_draft.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_2/oncoanalyser-dna-complete-to-sash-ready/step_functions_templates/oncoanalyser_dna_complete_to_sash_ready_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_3/oncoanalyser-dna-or-rna-to-oncoanalyser-both-ready/step_functions_templates/oncoanalyser_dna_or_rna_complete_to_oncoanalyser_both_ready_sfn_template.asl.json
  lib/workload/stateless/stacks/transcriptome-pipeline-manager/step_functions_templates/set_wts_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/transcriptome-pipeline-manager/step_functions_templates/set_wts_cwl_outputs_sfn.asl.json
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/step_functions_templates/set_tn_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/step_functions_templates/set_tn_cwl_outputs_sfn.asl.json
  lib/workload/stateless/stacks/umccrise-pipeline-manager/step_functions_templates/set_umccrise_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/umccrise-pipeline-manager/step_functions_templates/set_umccrise_cwl_outputs_sfn.asl.json
  lib/workload/stateless/stacks/wgts-alignment-qc-pipeline-manager/step_functions_templates/set_wgts_alignment_qc_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/wgts-alignment-qc-pipeline-manager/step_functions_templates/set_wgts_alignment_qc_cwl_outputs_sfn.asl.json
Labels: bug

#632 Allow samplesheet overwrite
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/upload_samplesheet_to_cache_dir_py/upload_samplesheet_to_cache_dir.py
Labels: bug
