Repository umccr/orcabus, pull requests merged in 2024-11, with the labels that each got.

#635 Need to collect camelCase orcabus Id when retrieving object from metadata manager
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/step_functions_templates/umccrise_and_wts_complete_to_rnasum_draft.asl.json
Labels: bug

#627 Feat(MM): Add Sync Metadata Endpoint
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/load_from_csv.py
  lib/workload/stateless/stacks/metadata-manager/app/migrations/0002_remove_historicalcontact_history_user_and_more.py
  lib/workload/stateless/stacks/metadata-manager/app/models/base.py
  lib/workload/stateless/stacks/metadata-manager/app/models/contact.py
  lib/workload/stateless/stacks/metadata-manager/app/models/individual.py
  lib/workload/stateless/stacks/metadata-manager/app/models/library.py
  lib/workload/stateless/stacks/metadata-manager/app/models/project.py
  lib/workload/stateless/stacks/metadata-manager/app/models/sample.py
  lib/workload/stateless/stacks/metadata-manager/app/models/subject.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/library.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/project.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/subject.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/sync.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/urls/base.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/__init__.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/sync.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/utils.py
  lib/workload/stateless/stacks/metadata-manager/deploy/README.md
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-load-custom-csv/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-sync-gsheet/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
  lib/workload/stateless/stacks/metadata-manager/handler/load_custom_metadata_csv.py
  lib/workload/stateless/stacks/metadata-manager/handler/sync_tracking_sheet.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/load_csv_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
  test/stateless/deployment.test.ts
Labels: feature

#628 Feat/analysis run api update
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_comment.py
Labels: feature, fix

#636 Delete partial files before retrying copy job
  lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
  lib/workload/components/icav2-copy-files/step_functions_templates/copy_files_sfn.asl.json
Labels: bug

#624 Added ora file decompression fastq pair component
  .gitattributes
  cdk.context.json
  config/config.ts
  config/constants.ts
  config/stacks/oraCompressionPipelineManager.ts
  config/stacks/oraDecompressionPipelineManager.ts
  lib/workload/components/icav2-copy-files-batch/index.ts
  lib/workload/components/icav2-copy-files/index.ts
  lib/workload/components/ora-file-decompression-fq-pair-sfn/index.ts
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/Dockerfile
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/binaries/orad.tar.gz
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/docker-entrypoint.sh
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/scripts/download_icav2_file.py
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/scripts/get_aws_credentials_access.py
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/scripts/get_icav2_download_url.py
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/scripts/get_s3_uri.py
  lib/workload/components/python-lambda-get-metadata-objects-from-samplesheet/index.ts
  lib/workload/components/python-lambda-uuid-generator-function/Readme.md
  lib/workload/components/python-lambda-uuid-generator-function/index.ts
  lib/workload/components/python-lambda-uuid-generator-function/uuid_py/requirements.txt
  lib/workload/components/python-lambda-uuid-generator-function/uuid_py/run_uuid.py
  lib/workload/components/sfn-generate-workflowrunstatechange-ready-event/index.ts
  lib/workload/components/sfn-icav2-ready-event-handler/index.ts
  lib/workload/components/sfn-icav2-state-change-event-handler/index.ts
  lib/workload/components/sfn-workflowdraftrunstatechange-common-preamble/index.ts
  lib/workload/stateful/stacks/ora-decompression-dynamodb/deploy/stack.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/deploy/constructs/bclconvert-interop-qc-step-function/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/Readme.md
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_file_sizes_for_fastq_list_rows_py/merge_file_sizes_for_fastq_list_rows.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_file_sizes_for_fastq_list_rows_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/set_outputs_json_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/set_outputs_json_py/set_outputs_json.py
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/fastq_list_row_compression_event.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json
  lib/workload/stateless/stacks/ora-decompression-manager/README.md
  lib/workload/stateless/stacks/ora-decompression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-decompression-manager/step_functions_templates/ora_decompression_manager_sfn_template.asl.json
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#634 Upgrade memory for pieriandx glue lambdas
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/lambdas/get_data_from_redcap_py/get_data_from_redcap.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/lambdas/get_deidentified_case_metadata_py/get_deidentified_case_metadata.py
Labels: fix

#642 CodeBuild doesn't support git-lfs
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/Dockerfile
Labels: bug

#646 Only save payload if present
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/utils.py
Labels: fix

#638 Add analysis size option per microservice
  lib/workload/components/sfn-icav2-ready-event-handler/icav2_launch_pipeline_lambda_py/icav2_launch_pipeline_lambda.py
  lib/workload/components/sfn-icav2-ready-event-handler/index.ts
  lib/workload/components/sfn-icav2-ready-event-handler/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
Labels: fix

#643 Manually transfer files that are smaller than 8 MiB or dont have an etag
  lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
Labels: fix

#648 Need to set 'keep_flowcell_layout' to true for wrapica collection of runinfo xml
  lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/runinfo/runinfo_helper.py
  lib/workload/stateless/stacks/bclconvert-manager/translator_service/helper/samplesheet/samplesheet_helper.py
Labels: fix

#649 Fix (MM): Allow nullable description for sync
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/sync.py
Labels: fix

#650 Fix WRSC not having a payload
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py
Labels: fix

#652 Set cttsov2 icav2 storage configuration to LARGE
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
Labels: bug, fix

#654 Pull the snomed databases from github if they're not on the local system
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/generate_pieriandx_objects_py/generate_pieriandx_objects.py
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/layers/src/pieriandx_pipeline_tools/pieriandx_lookup/get_disease_label.py
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/layers/src/pieriandx_pipeline_tools/pieriandx_lookup/get_specimen_label.py
Labels: fix

#656 fix-ora-compression-manager
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_file_sizes_for_fastq_list_rows_py/merge_file_sizes_for_fastq_list_rows.py
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/fastq_list_row_compression_event.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json
Labels: bug

#658 Prevent the ntc samples running through cttsov2
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-library-dbs/index.ts
Labels: change request

#659 PierianDx Production Fixes
  config/constants.ts
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/deploy/index.ts
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/generate_output_data_payload_py/generate_output_data_payload.py
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/get_informaticsjob_and_report_status_py/get_informaticsjob_and_report_status.py
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/upload_pieriandx_sample_data_to_s3_py/upload_pieriandx_sample_data_to_s3.py
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/layers/src/pieriandx_pipeline_tools/utils/s3_helpers.py
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/launch_pieriandx.asl.json
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/step_function_templates/monitor_runs.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_2/cttso-v2-output-to-pieriandx-ready-event/lambdas/get_data_from_redcap_py/get_data_from_redcap.py
Labels: fix

#661 HotFix(authorization-manager): Sanitize Authorization Header
  config/constants.ts
  config/stacks/authorizationManager.ts
  lib/workload/components/api-gateway/README.md
  lib/workload/components/api-gateway/index.ts
  lib/workload/stateful/stacks/authorization-manager/README.md
  lib/workload/stateful/stacks/authorization-manager/http-lambda-authorizer/http_authorizer.py
  lib/workload/stateful/stacks/authorization-manager/stack.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  test/stateful/pipeline/deployment.test.ts
Labels: fix

#665 Update dragen somatic pipeline id
  config/constants.ts
  lib/workload/stateless/stacks/tumor-normal-pipeline-manager/lambdas/get_boolean_parameters_from_event_input_py/get_boolean_parameters_from_event_input.py
Labels: fix

#667 Fixed oncoanalyser Batch trigger initial status SUBMITTED
  lib/workload/components/sfn-nf-batch-ready-event-handler/step_functions_templates/launch_nextflow_pipeline_template.asl.json
Labels: fix

#671 Wrong typescript boolean logic which meant there was no event rule
  lib/workload/components/sfn-nf-batch-ready-event-handler/index.ts
Labels: fix

#674 Fix literal placeholders in nf step functions
  lib/workload/components/sfn-nf-batch-state-change-event-handler/index.ts
  lib/workload/components/sfn-nf-batch-state-change-event-handler/step_functions_templates/capture_aws_batch_completion_events_template.asl.json
Labels: bug

#670 hotfix(filemanager): add permissions that allow API/inventory functions to access `pipeline-*-cache` buckets
  config/stacks/fileManager.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
Labels: fix, filemanager

#680 Sanitise subject id for oncoanalyser / sash / nf workflows
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/lambdas/generate_dna_payload_py/generate_dna_payload.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/lambdas/generate_rna_payload_py/generate_rna_payload.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_2/oncoanalyser-dna-complete-to-sash-ready/lambdas/generate_sash_payload_py/generate_sash_payload.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_3/oncoanalyser-dna-or-rna-to-oncoanalyser-both-ready/lambdas/get_oncoanalyser_dna_rna_payload_py/get_oncoanalyser_dna_rna_payload.py
Labels: bug, fix

#678 Update v2 samplesheet maker version
  lib/workload/stateless/stacks/bclconvert-manager/deps/requirements.txt
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/upload_samplesheet_to_cache_dir_py/requirements.txt
Labels: fix

#684 Fix Rnasum dataset input parameter
  lib/workload/stateless/stacks/rnasum-pipeline-manager/step_functions_templates/set_rnasum_cwl_inputs_sfn.asl.json
Labels: bug, fix

#666 Setup to rearrange the outputs for the ora compression manager
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/set_outputs_json_py/set_outputs_json.py
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/fastq_list_row_compression_event.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json
Labels: change request

#686 Chore(mm): Miscellaneous Update
  lib/workload/stateless/stacks/metadata-manager/app/serializers/project.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/project.py
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
  lib/workload/stateless/stacks/metadata-manager/docs/schema.drawio.svg
Labels: refactor

#685 Update rnasum pipeline version to 1.1.5
  config/constants.ts
  config/stacks/rnasumPipelineManager.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/index.ts
Labels: change request, fix

#688 fix(filemanager): longer presigned URLs
  lib/workload/components/named-lambda-role/index.ts
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
Labels: fix, filemanager

#692 Added lambda layer for workflows API endpoint + RNASum Lambda
  lib/workload/components/python-workflow-tools-layer/index.ts
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/poetry.lock
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/pyproject.toml
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/src/workflow_tools/utils/__init__.py
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/src/workflow_tools/utils/aws_helpers.py
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/src/workflow_tools/utils/globals.py
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/src/workflow_tools/utils/payload_helpers.py
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/src/workflow_tools/utils/requests_helpers.py
  lib/workload/components/python-workflow-tools-layer/workflow_tools_layer/src/workflow_tools/utils/workflow_run_helpers.py
  lib/workload/stateless/stacks/rnasum-pipeline-manager/deploy/index.ts
  lib/workload/stateless/stacks/rnasum-pipeline-manager/lambdas/rerun_with_new_dataset_py/rerun_with_new_dataset.py
Labels: feature

#702 Fix rnasum rerun lambda
  lib/workload/stateless/stacks/rnasum-pipeline-manager/deploy/index.ts
Labels: bug

#700 feat(filemanager): add fastq bucket to ingester event source
  config/constants.ts
  config/stacks/shared.ts
Labels: feature, platform

#706 add distinct to remove duplicate results
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
Labels: fix

#703 Allow validation only for ora decompression
  config/constants.ts
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/index.ts
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/lambdas/delete_icav2_cache_uri_py/delete_icav2_cache_uri.py
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/lambdas/delete_icav2_cache_uri_py/requirements.txt
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/lambdas/read_icav2_file_contents_py/read_icav2_file_contents.py
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/lambdas/read_icav2_file_contents_py/requirements.txt
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/get_raw_md5sum_for_fastq_gzip_pair_template.asl.json
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/tasks/gzip_to_raw_md5sum/Dockerfile
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/tasks/gzip_to_raw_md5sum/docker-entrypoint.sh
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/tasks/gzip_to_raw_md5sum/scripts/get_aws_credentials_access.py
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/tasks/gzip_to_raw_md5sum/scripts/get_icav2_download_url.py
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/tasks/gzip_to_raw_md5sum/scripts/get_s3_uri.py
  lib/workload/components/icav2-copy-files-batch/index.ts
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/Dockerfile
  lib/workload/components/ora-file-decompression-fq-pair-sfn/tasks/ora_decompression/docker-entrypoint.sh
  lib/workload/components/sfn-generate-workflowrunstatechange-ready-event/index.ts
  lib/workload/components/sfn-icav2-ready-event-handler/index.ts
  lib/workload/components/sfn-icav2-state-change-event-handler/index.ts
  lib/workload/components/sfn-icav2-state-change-event-handler/step_functions_templates/icav2_get_workflow_status_and_raise_internal_event.asl.json
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/constructs/bssh-icav2-fastq-copy-manager/index.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_fastq_pairs_in_instrument_run_py/find_all_fastq_pairs_in_instrument_run.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_fastq_pairs_in_instrument_run_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_v2_samplesheets_in_instrument_run_py/find_all_v2_samplesheets_in_instrument_run.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_v2_samplesheets_in_instrument_run_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/get_file_size_from_uri_py/get_file_size_from_uri.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/get_file_size_from_uri_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_file_sizes_for_fastq_list_rows_py/merge_file_sizes_for_fastq_list_rows.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_rgids_with_fastq_list_rows_py/merge_rgids_with_fastq_list_rows.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/merge_rgids_with_fastq_list_rows_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/fastq_list_row_compression_event.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json
  lib/workload/stateless/stacks/ora-decompression-manager/deploy/index.ts
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/deploy/constructs/pieriandx_launch_step_function.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/elmer/part_1/bclconvert-succeeded-to-bssh-fastq-copy/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/gorilla/part_1/bclconvert-interop-qc-draft-event-maker/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_3/launch-oncoanalyser-ready-events/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_3/fastq-list-row-event-shower-complete-to-cttsov2-ready/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_3/fastq-list-rows-shower-complete-to-wgts-qc/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_3/library-qc-complete-db-to-tn-ready/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_3/library-qc-complete-to-wts/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/tn-complete-to-umccrise-draft/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_2/umccrise-and-wts-complete-to-rnasum-draft/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_2/oncoanalyser-dna-complete-to-sash-ready/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_3/oncoanalyser-dna-or-rna-to-oncoanalyser-both-ready/index.ts
Labels: feature

#713 Feat(wfm): `rnasum` rerun api
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/README.md
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/workflowrunstatechange/AWSEvent.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/workflowrunstatechange/LibraryRecord.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/workflowrunstatechange/Payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/workflowrunstatechange/WorkflowRunStateChange.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/workflowrunstatechange/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/executionservice/workflowrunstatechange/marshaller.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/workflowrunstatechange/AWSEvent.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/workflowrunstatechange/LibraryRecord.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/workflowrunstatechange/Payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/workflowrunstatechange/WorkflowRunStateChange.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/workflowrunstatechange/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/aws_event_bridge/workflowmanager/workflowrunstatechange/marshaller.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/utils.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run_action.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/factories.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_viewsets.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_action.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/transition_bcm_fastq_copy.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/emit_workflow_run_state_change.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py
Labels: feature

#715 Few lambda fixes
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_fastq_pairs_in_instrument_run_py/find_all_fastq_pairs_in_instrument_run.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_fastq_pairs_in_instrument_run_py/requirements.txt
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_v2_samplesheets_in_instrument_run_py/find_all_v2_samplesheets_in_instrument_run.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_v2_samplesheets_in_instrument_run_py/requirements.txt
Labels: bug

#714 Feat(pipeline): Disable Dev Automatic Deployment
  cdk.json
  lib/pipeline/statefulPipelineStack.ts
  lib/pipeline/statelessPipelineStack.ts
Labels: change request, platform

#716 Fix(MM): Add reason on history for `add` in m2m relationship
  lib/workload/stateless/stacks/metadata-manager/proc/service/load_csv_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
Labels: fix

#720 Rate limit ora compression workflow
  config/constants.ts
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/index.ts
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/get_raw_md5sum_for_fastq_gzip_pair_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/index.ts
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/ecs_task_rate_limiters_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/deploy/index.ts
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_gzips_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_ora_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/rate_limit_get_raw_md5sum_for_fastq_gzip_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/rate_limit_get_raw_md5sum_for_fastq_ora_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_outputs.asl.json
Labels: feature

#709 feat: dump postgres records
  Makefile
  compose.yml
  config/config.ts
  config/stacks/pgDD.ts
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/pg-dd/.dockerignore
  lib/workload/stateless/stacks/pg-dd/.env.example
  lib/workload/stateless/stacks/pg-dd/.gitignore
  lib/workload/stateless/stacks/pg-dd/Dockerfile
  lib/workload/stateless/stacks/pg-dd/Makefile
  lib/workload/stateless/stacks/pg-dd/README.md
  lib/workload/stateless/stacks/pg-dd/deploy/stack.ts
  lib/workload/stateless/stacks/pg-dd/pg_dd/__init__.py
  lib/workload/stateless/stacks/pg-dd/pg_dd/cli.py
  lib/workload/stateless/stacks/pg-dd/pg_dd/handler.py
  lib/workload/stateless/stacks/pg-dd/pg_dd/pg_dd.py
  lib/workload/stateless/stacks/pg-dd/poetry.lock
  lib/workload/stateless/stacks/pg-dd/pyproject.toml
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature, platform

#723 Feat(mm): Allow Library Filtered by Project
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py
Labels: feature

#731 Don't extend portal run id to sequencer run,
  lib/workload/stateless/stacks/pieriandx-pipeline-manager/lambdas/generate_pieriandx_objects_py/generate_pieriandx_objects.py
Labels: bug, fix

#730 Set sample type to ctDNA for cttsov2 triggers
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-library-dbs/index.ts
Labels: change request

#735 fix(data-migrate): set arch as ARM64
  lib/workload/stateless/stacks/data-migrate/deploy/stack.ts
Labels: platform, fix

#736 ORA Compression fixes for too large sfns, single indexed libraries
  lib/workload/components/gzip-raw-md5sum-fq-pair-sfn/step_functions_templates/get_raw_md5sum_for_fastq_gzip_pair_template.asl.json
  lib/workload/components/ora-file-decompression-fq-pair-sfn/step_functions_templates/decompress_ora_fastq_pair_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_fastq_pairs_in_instrument_run_py/find_all_fastq_pairs_in_instrument_run.py
  lib/workload/stateless/stacks/ora-compression-manager/lambdas/find_all_v2_samplesheets_in_instrument_run_py/find_all_v2_samplesheets_in_instrument_run.py
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/get_raw_md5sum_for_all_fastq_gzips_sfn_template.asl.json
  lib/workload/stateless/stacks/ora-compression-manager/step_functions_templates/set_compression_inputs.asl.json
Labels: bug
