Repository umccr/orcabus, pull requests merged in 2024-05, with the labels that each got.

#144 Feature/bssh icav2 fastq copy manager
  config/config.ts
  config/constants.ts
  config/stacks/bsRunsUploadManager.ts
  config/stacks/bsshIcav2FastqCopyManager.ts
  config/stacks/icav2CopyBatchUtility.ts
  lib/workload/components/python-lambda-layer/index.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/Readme.md
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/constructs/bssh-icav2-fastq-copy-manager/index.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/images/step_functions_image.png
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/lambdas/query_bclconvert_outputs_handler/handler.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/poetry.lock
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/pyproject.toml
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/__init__.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/__init__.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/aws_ssm_helpers.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/compression_helpers.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/directory_helper.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/globals.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/icav2_analysis_helpers.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/logger.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/manifest_helper.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/sample_helper.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/samplesheet_helper.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/xml_helpers.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/step_functions_templates/bclconvert_success_event_state_machine.json
  lib/workload/stateless/stacks/icav2-copy-batch-utility/deploy/constructs/icav2-copy-batch-utility/index.ts
  lib/workload/stateless/stacks/icav2-copy-batch-utility/deploy/stack.ts
  lib/workload/stateless/stacks/postgres-manager/yarn.lock
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#258 Deprecated initial POC event schemas
  config/event_schemas/BclConvertWorkflowRequest.json
  config/event_schemas/DragenWgsQcWorkflowRequest.json
  config/event_schemas/WesLaunchRequest.json
  config/event_schemas/WorkflowRequest.json
Labels: refactor

#263 Fixed basespace runs upload input field typo `run_volume_name`
  lib/workload/stateless/stacks/bs-runs-upload-manager/step_functions_templates/bs_runs_upload_step_functions_template.json
Labels: fix

#264 Fix: PG-Manager Build Install
  Makefile
  lib/workload/stateless/stacks/postgres-manager/.gitignore
  lib/workload/stateless/stacks/postgres-manager/.yarnrc.yml
  lib/workload/stateless/stacks/postgres-manager/deploy/lambda-build.Dockerfile
  lib/workload/stateless/stacks/postgres-manager/deploy/stack.ts
  lib/workload/stateless/stacks/postgres-manager/package.json
  lib/workload/stateless/stacks/postgres-manager/yarn.lock
Labels: fix

#266 Refactored and deployed event schema stack
  config/config.ts
  config/constants.ts
  config/event_schemas/WorkflowRunStateChange.json
  config/stacks/schema.ts
  config/stacks/shared.ts
  docs/event-schemas/srm/SequenceRunStateChange.json
  docs/event-schemas/srm/example/SRSC__started.json
  docs/event-schemas/srm/example/SRSC__succeeded.json
  lib/workload/stateless/schema/component.ts
  lib/workload/stateless/stacks/schema/README.md
  lib/workload/stateless/stacks/schema/stack.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: change request, refactor

#267 Fixed stateful unittest constants `schemaRegistryName`
  test/stateful/shared/schemaRegistryConstruct.test.ts
Labels: fix

#268 fix(metadata-manager): Fix API GW && Custom Resource for Migration Lambda
  config/constants.ts
  config/stacks/metadataManager.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/README.md
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-migration/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
  lib/workload/stateless/stacks/metadata-manager/handler/migrate.py
Labels: fix

#269 Fix(MetadataManager): Deployment Test Supression
  test/stateless/deployment.test.ts
Labels: fix

#271 Fix(metadata-manager): Custom Resource Deployment
  lib/workload/stateless/stacks/metadata-manager/handler/migrate.py
Labels: fix

#145 Feature/cttso icav2 step function branch
  config/config.ts
  config/constants.ts
  config/stacks/cttsov2Icav2PipelineManager.ts
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/index.ts
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/step_functions_templates/icav2_get_workflow_status_and_raise_internal_event.asl.json
  lib/workload/components/dynamodb-icav2-table/index.ts
  lib/workload/stateful/stacks/cttso-v2-pipeline-dynamo-db/Readme.md
  lib/workload/stateful/stacks/cttso-v2-pipeline-dynamo-db/deploy/stack.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/Readme.md
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/stack.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/images/step_functions_image.png
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/generate_and_trim_cttso_samplesheet_dict/handler.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/generate_copy_manifest_dict/handler.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/generate_db_uuid/handler.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/launch_cttso_nextflow_pipeline/handler.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/upload_samplesheet_to_cache_dir/handler.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/poetry.lock
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/pyproject.toml
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/src/cttso_v2_pipeline_manager_tools/__init__.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/src/cttso_v2_pipeline_manager_tools/utils/__init__.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/src/cttso_v2_pipeline_manager_tools/utils/aws_ssm_helpers.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/src/cttso_v2_pipeline_manager_tools/utils/compression_helpers.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/layers/src/cttso_v2_pipeline_manager_tools/utils/path_helpers.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/cttso_v2_launch_workflow_state_machine.asl.json
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#281 Use 'currentVersion' for lambda object to resolve the cdk nag issue
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
Labels: fix

#278 Bumped SequenceRunManager dependencies
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-test.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
Labels: dependencies

#286 Remove cdk.out assets to prevent synth output
  lib/pipeline/statelessPipelineStack.ts
Labels: bug, blocker

#279 Updated Basespace Runs Upload Manager to align with SequenceRunStateChange schema
  lib/workload/stateless/stacks/bs-runs-upload-manager/Readme.md
  lib/workload/stateless/stacks/bs-runs-upload-manager/step_functions_templates/bs_runs_upload_step_functions_template.json
Labels: change request

#277 Updated SequenceRunManager service to align with SequenceRunStateChange
  lib/workload/stateless/stacks/bs-runs-upload-manager/Readme.md
  lib/workload/stateless/stacks/bs-runs-upload-manager/step_functions_templates/bs_runs_upload_step_functions_template.json
  lib/workload/stateless/stacks/sequence-run-manager/Makefile
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-test.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/AWSEvent.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/SequenceRunStateChange.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequencerunstatechange/marshaller.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_sequence_domain.py
Labels: change request

#288 Updated django-api skel profile
  docs/developer/DJANGO_API.md
  skel/django-api/Makefile
  skel/django-api/README.md
  skel/django-api/api.py
  skel/django-api/component.ts
  skel/django-api/compose.yml
  skel/django-api/deploy/README.md
  skel/django-api/deploy/stack.ts
  skel/django-api/deps/requirements-dev.txt
  skel/django-api/deps/requirements-test.txt
  skel/django-api/deps/requirements.txt
  skel/django-api/manage.py
  skel/django-api/migrate.py
  skel/django-api/project_name/__init__.py
  skel/django-api/project_name/fields.py
  skel/django-api/project_name/migrations/__init__.py
  skel/django-api/project_name/models/__init__.py
  skel/django-api/project_name/models/base.py
  skel/django-api/project_name/models/helloworld.py
  skel/django-api/project_name/pagination.py
  skel/django-api/project_name/renderers.py
  skel/django-api/project_name/routers.py
  skel/django-api/project_name/serializers.py
  skel/django-api/project_name/settings/__init__.py
  skel/django-api/project_name/settings/aws.py
  skel/django-api/project_name/settings/base.py
  skel/django-api/project_name/settings/it.py
  skel/django-api/project_name/settings/local.py
  skel/django-api/project_name/tests/__init__.py
  skel/django-api/project_name/tests/test_base.py
  skel/django-api/project_name/tests/test_models.py
  skel/django-api/project_name/tests/test_viewsets.py
  skel/django-api/project_name/urls/__init__.py
  skel/django-api/project_name/urls/base.py
  skel/django-api/project_name/urls/local.py
  skel/django-api/project_name/viewsets/__init__.py
  skel/django-api/project_name/viewsets/helloworld.py
  skel/django-api/project_name/wsgi.py
  skel/django-api/project_name_proc/__init__.py
  skel/django-api/project_name_proc/lambdas/__init__.py
  skel/django-api/project_name_proc/lambdas/hello_proc.py
  skel/django-api/project_name_proc/services/__init__.py
  skel/django-api/project_name_proc/services/hello_srv.py
  skel/django-api/project_name_proc/tests/__init__.py
  skel/django-api/project_name_proc/tests/case.py
  skel/django-api/project_name_proc/tests/test_hello_proc.py
  skel/django-api/project_name_proc/tests/test_hello_srv.py
  skel/django-api/src/project_name/__init__.py
  skel/django-api/src/requirements.txt
Labels: documentation, platform

#287 Revert "Remove cdk.out assets to prevent synth output"
  lib/pipeline/statelessPipelineStack.ts
Labels: bug, platform, blocker

#291 Fixed WorkflowRunStateChange schema required field
  docs/event-schemas/wfm/WorkflowRunStateChange.json
Labels: bug, fix

#290 feat: Refine Testing Configuration
  .github/workflows/prbuild.yml
  README.md
  lib/pipeline/statelessPipelineStack.ts
  test/stateless/pipeline.test.ts
Labels: feature

#204 icav2 event translator
  Makefile
  config/config.ts
  config/stacks/icav2EventTranslator.ts
  docs/event-schemas/wfm/example/WRSC__bcm__bssh_bcl_convert.json
  lib/workload/components/dynamodb-icav2-table/index.ts
  lib/workload/stateful/stacks/icav2-event-translator-dynamo-db/README.md
  lib/workload/stateful/stacks/icav2-event-translator-dynamo-db/deploy/stack.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/icav2-event-translator/README.md
  lib/workload/stateless/stacks/icav2-event-translator/deploy/stack.ts
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/Makefile
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/__init__.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/deps/requirements-test.txt
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/icav2_event_translator.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/tests/__init__.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/tests/test_icav2_event_translator.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/workflowrunstatechange/AWSEvent.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/workflowrunstatechange/Payload.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/workflowrunstatechange/WorkflowRunStateChange.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/workflowrunstatechange/__init__.py
  lib/workload/stateless/stacks/icav2-event-translator/translator_service/workflowrunstatechange/marshaller.py
  lib/workload/stateless/statelessStackCollectionClass.ts
  test/stateful/ica-event-pipe/icaEventPipeConstruct.test.ts
  test/stateful/icav2-event-translator-dynamo-db/icav2EventTranslatorDynamoDB.test.ts
Labels: feature

#292 Fix ica event translator build issue
  config/stacks/icav2EventTranslator.ts
  lib/workload/stateless/stacks/icav2-event-translator/deploy/stack.ts
Labels: fix

#295 Add Events system to bssh fastq copy manager (and deprecate icav2 copy batch utility stack)
  config/config.ts
  config/constants.ts
  config/stacks/bsshIcav2FastqCopyManager.ts
  config/stacks/cttsov2Icav2PipelineManager.ts
  config/stacks/icav2CopyBatchUtility.ts
  lib/workload/components/icav2-copy-files-batch/index.ts
  lib/workload/components/icav2-copy-files-batch/manifest_handler_lambda_py/manifest_handler_lambda.py
  lib/workload/components/icav2-copy-files-batch/step_functions_templates/copy_files_batch_sfn.asl.json
  lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/check_or_launch_job_lambda.py
  lib/workload/components/icav2-copy-files/check_or_launch_job_lambda_py/requirements.txt
  lib/workload/components/icav2-copy-files/index.ts
  lib/workload/components/icav2-copy-files/step_functions_templates/copy_files_sfn.asl.json
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/Readme.md
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/constructs/bssh-icav2-fastq-copy-manager/index.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/lambdas/query_bclconvert_outputs_handler_lambda_py/query_bclconvert_outputs_handler_lambda.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/directory_helper.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/step_functions_templates/bclconvert_success_event_state_machine.json
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/constructs/cttsov2-icav2-manager/index.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/deploy/stack.ts
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/lambdas/generate_copy_manifest_dict_py/generate_copy_manifest_dict.py
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json
  lib/workload/stateless/stacks/icav2-copy-batch-utility/.gitignore
  lib/workload/stateless/stacks/icav2-copy-batch-utility/.npmignore
  lib/workload/stateless/stacks/icav2-copy-batch-utility/Readme.md
  lib/workload/stateless/stacks/icav2-copy-batch-utility/deploy/constructs/icav2-copy-batch-utility/index.ts
  lib/workload/stateless/stacks/icav2-copy-batch-utility/deploy/stack.ts
  lib/workload/stateless/stacks/icav2-copy-batch-utility/images/step_functions_tool_graph.png
  lib/workload/stateless/stacks/icav2-copy-batch-utility/images/step_functions_wf_graph.png
  lib/workload/stateless/stacks/icav2-copy-batch-utility/lambdas/check_or_launch_job/handler.py
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/poetry.lock
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/pyproject.toml
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/src/icav2_copy_batch_utility_tools/__init__.py
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/src/icav2_copy_batch_utility_tools/utils/__init__.py
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/src/icav2_copy_batch_utility_tools/utils/aws_ssm_helpers.py
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/src/icav2_copy_batch_utility_tools/utils/compression_helpers.py
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/src/icav2_copy_batch_utility_tools/utils/globals.py
  lib/workload/stateless/stacks/icav2-copy-batch-utility/layers/src/icav2_copy_batch_utility_tools/utils/job_helpers.py
  lib/workload/stateless/stacks/icav2-event-translator/README.md
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#306 Refined WorkflowManager database models
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/migrations/0001_initial.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run.py
Labels: change request

#309 Updated SequenceRunStateChange schema
  config/stacks/schema.ts
  docs/event-schemas/sequencerunmanager/SequenceRunStateChange.json
  docs/event-schemas/sequencerunmanager/example/SRSC__started.json
  docs/event-schemas/sequencerunmanager/example/SRSC__succeeded.json
Labels: change request

#310 feat(filemanager): add Parquet and Orc support to inventory
  .secrets.baseline
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/orc_inventory.orc
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/orc_inventory_manifest.checksum
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/orc_inventory_manifest.json
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/parquet_inventory.parquet
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/parquet_inventory_manifest.checksum
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/data/parquet_inventory_manifest.json
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/main.rs
Labels: feature

#308 Updated WorkflowRunStateChange schema
  config/stacks/schema.ts
  docs/event-schemas/sequencerunmanager/SequenceRunStateChange.json
  docs/event-schemas/sequencerunmanager/example/SRSC__started.json
  docs/event-schemas/sequencerunmanager/example/SRSC__succeeded.json
  docs/event-schemas/wfm/example/WRSC__bcm__bssh_bcl_convert.json
  docs/event-schemas/wfm/example/WRSC__fqcp__bssh_icav2_fastq_copy.json
  docs/event-schemas/wfm/example/WRSC__wfm__bssh_icav2_fastq_copy.json
  docs/event-schemas/workflowmanager/WorkflowRunStateChange.json
  docs/event-schemas/workflowmanager/example/WRSC__example1.json
Labels: change request

#307 Added documentation on Event Schema and Namespace guide
  README.md
  docs/event-schemas/README.md
Labels: documentation

#311 Feature/data schema
  config/stacks/schema.ts
  docs/schemas/README.md
  docs/schemas/data/bclconvertmanager/PayloadDataSucceeded.json
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataReady.json
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataSucceeded.json
  docs/schemas/events/executionservice/WorkflowRunStateChange.json
  docs/schemas/events/executionservice/example/WRSC__example1.json
  docs/schemas/events/executionservice/example/WRSC__example2.json
  docs/schemas/events/sequencerunmanager/SequenceRunStateChange.json
  docs/schemas/events/sequencerunmanager/example/SRSC__started.json
  docs/schemas/events/sequencerunmanager/example/SRSC__succeeded.json
  docs/schemas/events/workflowmanager/WorkflowRunStateChange.json
  docs/schemas/events/workflowmanager/example/WRSC__example1.json
  docs/schemas/events/workflowmanager/example/WRSC__example2.json
Labels: documentation, feature, change request

#320 Added data schema registry and data schema deployment stack
  config/config.ts
  config/constants.ts
  config/stacks/schema/data.ts
  config/stacks/schema/events.ts
  config/stacks/shared.ts
  docs/schemas/README.md
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataReady.json
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataSucceeded.json
  lib/workload/stateful/stacks/shared/stack.ts
  lib/workload/stateless/stacks/schema/README.md
  lib/workload/stateless/statelessStackCollectionClass.ts
  test/stateful/shared/schemaRegistryConstruct.test.ts
Labels: feature, change request

#321 fix: filemanager delete marker
  lib/workload/stateless/stacks/filemanager/database/migrations/0003_add_is_delete_marker.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_deleted_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/main.rs
Labels: fix, filemanager

#327 Update libumccr version to 0.4.0rc3
  lib/workload/stateless/stacks/workflow-manager/deps/requirements.txt
Labels: fix

#329 Fix workflow manager issues when handling WRSC events
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/transition_bcm_fastq_copy.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/emit_workflow_run_state_change.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/get_workflow_run.py
Labels: fix

#330 Refactored schemas to JSON Schema
  Brewfile
  config/stacks/schema/data.ts
  config/stacks/schema/events.ts
  docs/schemas/data/bclconvertmanager/Makefile
  docs/schemas/data/bclconvertmanager/PayloadDataSucceeded.json
  docs/schemas/data/bclconvertmanager/PayloadDataSucceeded.schema.json
  docs/schemas/data/bclconvertmanager/example/PayloadDataSucceeded__example1.json
  docs/schemas/data/bsshicav2fastqcopymanager/Makefile
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataReady.json
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataReady.schema.json
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataSucceeded.json
  docs/schemas/data/bsshicav2fastqcopymanager/PayloadDataSucceeded.schema.json
  docs/schemas/data/bsshicav2fastqcopymanager/example/PayloadDataReady__example1.json
  docs/schemas/data/bsshicav2fastqcopymanager/example/PayloadDataSucceeded__example1.json
  docs/schemas/events/executionservice/Makefile
  docs/schemas/events/executionservice/WorkflowRunStateChange.json
  docs/schemas/events/executionservice/WorkflowRunStateChange.schema.json
  docs/schemas/events/sequencerunmanager/Makefile
  docs/schemas/events/sequencerunmanager/SequenceRunStateChange.json
  docs/schemas/events/sequencerunmanager/SequenceRunStateChange.schema.json
  docs/schemas/events/workflowmanager/Makefile
  docs/schemas/events/workflowmanager/WorkflowRunStateChange.json
  docs/schemas/events/workflowmanager/WorkflowRunStateChange.schema.json
  docs/schemas/events/workflowmanager/example/WRSC__example2.json
Labels: change request, refactor

#335 update docs for bcl convert manger data
  lib/workload/stateful/stacks/bclconvert-dynamo-db/README.md
  lib/workload/stateless/stacks/bclconvert-manager/README.md
Labels: fix

#336 fix bugs for non-succeed event and update unit
  lib/workload/stateless/stacks/bclconvert-manager/README.md
  lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py
  lib/workload/stateless/stacks/bclconvert-manager/translator_service/tests/test_icav2_event_translator.py
Labels: fix
