Repository umccr/orcabus, pull requests merged in 2024-02, with the labels that each got.

#101 feat(filemanager): move SQS and DLQ to stateful stack
  config/constants.ts
  lib/workload/orcabus-stateful-stack.ts
  lib/workload/orcabus-stateless-stack.ts
  lib/workload/stateful/event_source/component.ts
  test/stateful/eventSourceConstruct.test.ts
Labels: feature, filemanager

#93 feat(filemanager): ensure events are ingested in the correct order
  lib/workload/stateful/filemanager/README.md
  lib/workload/stateful/filemanager/database/migrations/0001_add_object_table.sql
  lib/workload/stateful/filemanager/database/migrations/0002_add_s3_object_table.sql
  lib/workload/stateful/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateful/filemanager/database/queries/ingester/aws/insert_s3_deleted_objects.sql
  lib/workload/stateful/filemanager/database/queries/ingester/aws/update_deleted.sql
  lib/workload/stateful/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateful/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateful/filemanager/database/queries/ingester/insert_objects.sql
  lib/workload/stateful/filemanager/docs/ARCHITECTURE.md
  lib/workload/stateful/filemanager/filemanager-ingest-lambda/src/main.rs
  lib/workload/stateful/filemanager/filemanager-migrate-lambda/src/main.rs
  lib/workload/stateful/filemanager/filemanager/README.md
  lib/workload/stateful/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateful/filemanager/filemanager/src/clients/aws/sqs.rs
  lib/workload/stateful/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateful/filemanager/filemanager/src/database/aws/migration.rs
  lib/workload/stateful/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateful/filemanager/filemanager/src/env.rs
  lib/workload/stateful/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateful/filemanager/filemanager/src/events/aws/collector_builder.rs
  lib/workload/stateful/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateful/filemanager/filemanager/src/handlers/aws.rs
Labels: feature, filemanager

#118 fix: queue service name and secret name
  config/constants.ts
  lib/workload/orcabus-stateless-stack.ts
Labels: fix

#121 fix(filemanager): deserialize event bridge messages
  lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
Labels: fix

#125 fix(filemanager): correctly deal with null version_id
  lib/workload/stateless/filemanager/database/migrations/0002_add_s3_object_table.sql
  lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/filemanager/filemanager/src/handlers/aws.rs
Labels: fix, filemanager

#126 postgres-manager: Initiate postgres-manager
  .github/workflows/prbuild.yml
  config/constants.ts
  lib/workload/orcabus-stateless-stack.ts
  lib/workload/stateful/database/component.ts
  lib/workload/stateless/postgres_manager/.gitignore
  lib/workload/stateless/postgres_manager/README.md
  lib/workload/stateless/postgres_manager/construct/postgresManager.ts
  lib/workload/stateless/postgres_manager/function/alter-pg-db-owner.ts
  lib/workload/stateless/postgres_manager/function/create-pg-db.ts
  lib/workload/stateless/postgres_manager/function/create-pg-iam-role.ts
  lib/workload/stateless/postgres_manager/function/create-pg-login-role.ts
  lib/workload/stateless/postgres_manager/function/utils.ts
  lib/workload/stateless/postgres_manager/package.json
  lib/workload/stateless/postgres_manager/yarn.lock
Labels: feature
