Repository umccr/orcabus, pull requests merged in 2024-08, with the labels that each got.

#442 fix(filemanager): Dockerfile caching layer and debug build
  lib/workload/stateless/stacks/filemanager/Dockerfile
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
Labels: bug, devops

#434 Convert Oversized python lambdas to DockerImage Functions
  lib/workload/stateless/stacks/bclconvert-manager/Dockerfile
  lib/workload/stateless/stacks/bclconvert-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bclconvert-manager/deps/requirements.txt
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/lambdas/query_bclconvert_outputs_handler_py/Dockerfile
  lib/workload/stateless/stacks/transcriptome-pipeline-manager/lambdas/set_outputs_json_py/requirements.txt
Labels: bug

#445 Update ssm parameter pipeline constants for new icav2 pipelines
  config/constants.ts
Labels: feature

#448 Updated SRM processing to Singleton Lambda pattern
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
Labels: change request

#447 Improved Django skel template
  docs/developer/DJANGO_API.md
  skel/django-api/README.md
  skel/django-api/compose.yml
  skel/django-api/deps/requirements-dev.txt
  skel/django-api/deps/requirements-test.txt
  skel/django-api/deps/requirements.txt
  skel/django-api/project_name/pagination.py
  skel/django-api/project_name/settings/base.py
  skel/django-api/project_name/settings/local.py
  skel/django-api/project_name/urls/base.py
  skel/django-api/project_name/urls/local.py
Labels: documentation, dependencies

#450 Fixed minor stacky glues issues
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/gorilla/part_1/bclconvert-interop-qc-draft-event-maker/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/gorilla/part_2/bclconvert-interop-qc-input-maker/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_6/push-fastq-list-row-qc-complete-event/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_1/initialise-tn-subject-dbs/index.ts
Labels: fix

#452 Fix(SRM && WFM): Update OpenAPI Docs
  lib/workload/stateless/stacks/sequence-run-manager/README.md
  lib/workload/stateless/stacks/workflow-manager/README.md
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
Labels: fix

#457 feat: filemanager API wildcards
  lib/workload/stateless/stacks/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/docs/ATTRIBUTE_LINKING.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/README.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager

#466 Upgraded Django5.1 and bumped dependencies for MM, SRM, WFM services
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-full.txt
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-test.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements-test.txt
  lib/workload/stateless/stacks/sequence-run-manager/deps/requirements.txt
  lib/workload/stateless/stacks/workflow-manager/deps/requirements-dev.txt
  lib/workload/stateless/stacks/workflow-manager/deps/requirements-test.txt
  lib/workload/stateless/stacks/workflow-manager/deps/requirements.txt
Labels: dependencies

#465 refactor(filemanager): remove object table
  lib/workload/stateless/stacks/filemanager/database/migrations/0004_remove_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_deleted_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/insert_objects.sql
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/migration.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: refactor, filemanager

#467 fix(filemanager): local s3-load should not use `object`
  lib/workload/stateless/stacks/filemanager/Makefile
Labels: fix, filemanager

#469 Fixed Workflow Manager API filter by attributes
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
Labels: fix

#468 Harmonised API v1 versioning namespace base URL
  compose.yml
  lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/test_viewsets.py
  lib/workload/stateless/stacks/metadata-manager/app/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
Labels: change request

#471 Bumped dependencies
  .yarn/releases/yarn-4.3.0.cjs
  .yarn/releases/yarn-4.4.0.cjs
  .yarnrc.yml
  Makefile
  README.md
  package.json
  yarn.lock
Labels: dependencies

#472 refactor(filemanager): API style
  lib/workload/stateless/stacks/filemanager/.env.example
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_entities.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: refactor, filemanager

#475 feat: filemanager presigned route
  compose.yml
  lib/workload/stateless/stacks/filemanager/compose.yml
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager

#480 [skip ci]: Updated GH prbuild.yml
  .github/workflows/prbuild.yml
Labels: devops

#484 [skip ci]: Fixed GH prbuild.yml
  .github/workflows/prbuild.yml
Labels: devops

#485 [draft]: Added dependabot.yml config file
  .github/dependabot.yml
  .prettierignore
Labels: devops

#474 Bumped PGM dependencies
  lib/workload/stateful/stacks/postgres-manager/deploy/lambda-build.Dockerfile
  lib/workload/stateful/stacks/postgres-manager/package.json
  lib/workload/stateful/stacks/postgres-manager/yarn.lock
Labels: dependencies

#492 refactor(filemanager): misc simpler and clearer API
  lib/workload/stateless/stacks/filemanager/database/migrations/0005_rename_date.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_object_ids.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: refactor, filemanager

#499 fix(filemanager): presigned URL access
  compose.yml
  lib/workload/stateless/stacks/filemanager/Makefile
  lib/workload/stateless/stacks/filemanager/compose.yml
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
Labels: fix, filemanager

#501 Removed dependabot.yml config and revert to its default setting
  .github/dependabot.yml
  .github/workflows/prbuild.yml
  lib/workload/stateful/stacks/postgres-manager/package.json
  lib/workload/stateful/stacks/postgres-manager/yarn.lock
  package.json
  yarn.lock
Labels: devops, dependencies

#502 Django pagination fix
  lib/workload/stateless/stacks/metadata-manager/app/pagination.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/pagination.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/pagination.py
  skel/django-api/project_name/pagination.py
Labels: fix

#503 Add support for linked libraries to WRSC event schema
  docs/schemas/events/executionservice/WorkflowRunStateChange.schema.json
  docs/schemas/events/executionservice/example/WRSC__example1.json
  docs/schemas/events/workflowmanager/WorkflowRunStateChange.schema.json
  docs/schemas/events/workflowmanager/example/WRSC__example1.json
Labels: documentation, feature

#505 Stacky updates for generating umccrise events
  config/constants.ts
  config/stacks/stackyMcStackFace.ts
  lib/workload/stateful/stacks/stacky-mcstackface-dynamodb/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_5/library-qc-complete-db-to-tn-draft/lambdas/generate_draft_event_payload_py/generate_draft_event_payload.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_5/library-qc-complete-db-to-tn-draft/step_functions_templates/add_library_qc_complete_to_tn_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_4/library-qc-complete-to-wts-draft/lambdas/generate_draft_event_payload_py/generate_draft_event_payload.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_4/library-qc-complete-to-wts-draft/step_functions_templates/add_library_qc_complete_to_wts_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-subject-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-subject-dbs/step_functions_templates/initialise_umccrise_subject_db_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/initialise-umccrise-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_2/initialise-umccrise-library-dbs/step_functions_templates/initialise_umccrise_library_db_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_3/update-fastq-list-rows-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_3/update-fastq-list-rows-dbs/step_functions_templates/add_fastq_list_rows_db_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_4/tn-complete-to-umccrise-draft/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_4/tn-complete-to-umccrise-draft/lambdas/generate_draft_event_payload_py/generate_draft_event_payload.py
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_4/tn-complete-to-umccrise-draft/step_functions_templates/tn_complete_to_umccrise_draft_sfn_template.asl.json
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_5/umccrise-draft-to-ready/index.ts
Labels: feature

#504 Use the new metadata library endpoint for queries
  lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/library_helpers.py
  lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/specimen_helpers.py
  lib/workload/components/python-metadata-tools-layer/metadata_tools_layer/src/metadata_tools/utils/subject_helpers.py
Labels: change request

#506 initialised umccrise pipeline manager
  config/config.ts
  config/constants.ts
  config/stacks/umccrisePipelineManager.ts
  lib/workload/stateful/stacks/umccrise-pipeline-dynamo-db/deploy/stack.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/umccrise-pipeline-manager/deploy/index.ts
  lib/workload/stateless/stacks/umccrise-pipeline-manager/lambdas/get_cwl_object_from_s3_inputs_py/get_cwl_object_from_s3_inputs.py
  lib/workload/stateless/stacks/umccrise-pipeline-manager/lambdas/get_cwl_object_from_s3_inputs_py/requirements.txt
  lib/workload/stateless/stacks/umccrise-pipeline-manager/lambdas/get_outputs_py/get_outputs.py
  lib/workload/stateless/stacks/umccrise-pipeline-manager/step_functions_templates/set_umccrise_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/umccrise-pipeline-manager/step_functions_templates/set_umccrise_cwl_outputs_sfn.asl.json
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#507 Fix/filemanager api tidy
  compose.yml
  config/constants.ts
  config/stacks/fileManager.ts
  config/stacks/metadataManager.ts
  config/stacks/sequenceRunManager.ts
  config/stacks/workflowRunManager.ts
  lib/workload/components/api-gateway/index.ts
  lib/workload/stateless/stacks/filemanager/.env.example
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/compose.yml
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  skel/django-api/deploy/stack.ts
Labels: fix, filemanager

#508 metadata-manager: model refactoring
  lib/workload/stateless/stacks/metadata-manager/Dockerfile
  lib/workload/stateless/stacks/metadata-manager/Makefile
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/app/migrations/0001_initial.py
  lib/workload/stateless/stacks/metadata-manager/app/migrations/0002_alter_historicallibrary_coverage_and_more.py
  lib/workload/stateless/stacks/metadata-manager/app/migrations/0003_remove_specimen_subjects_historicalspecimen_subject_and_more.py
  lib/workload/stateless/stacks/metadata-manager/app/models/base.py
  lib/workload/stateless/stacks/metadata-manager/app/models/lab/individual.py
  lib/workload/stateless/stacks/metadata-manager/app/models/lab/library.py
  lib/workload/stateless/stacks/metadata-manager/app/models/lab/specimen.py
  lib/workload/stateless/stacks/metadata-manager/app/models/lab/subject.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/factories.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/test_models.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/test_viewsets.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
  lib/workload/stateless/stacks/metadata-manager/deps/requirements-slim.txt
  lib/workload/stateless/stacks/metadata-manager/docs/schema.drawio.svg
  lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py
Labels: change request

#510 Fixed metadata endpoint allow dot sep in PK
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
Labels: fix

#513 Feature/workflow library link
  .gitattributes
  lib/workload/stateless/stacks/workflow-manager/Makefile
  lib/workload/stateless/stacks/workflow-manager/README.md
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/migrations/0001_initial.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/factories.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/domain/executionservice/workflowrunstatechange/LibraryRecord.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/domain/executionservice/workflowrunstatechange/WorkflowRunStateChange.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/domain/executionservice/workflowrunstatechange/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/domain/workflowmanager/workflowrunstatechange/LibraryRecord.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/domain/workflowmanager/workflowrunstatechange/WorkflowRunStateChange.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/domain/workflowmanager/workflowrunstatechange/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/get_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_workflow_srv.py
Labels: feature

#514 refactor: filemanager indexes
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/database/migrations/0006_index.sql
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: refactor, filemanager

#519 fix: filemanager migration
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/migrate.ts
  lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-migrate-lambda/src/main.rs
Labels: fix, filemanager

#516 Fixed WorkflowRun State creation business logic
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
Labels: fix

#520 Fix Django OpenAPI Schema
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/library.py
Labels: fix

#515 filemanager: attributes route and misc CORS changes
  compose.yml
  lib/workload/stateless/stacks/filemanager/.env.example
  lib/workload/stateless/stacks/filemanager/compose.yml
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-inventory-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/build.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/wildcard.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/header.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager

#521 Fix/workflowrun state handling
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/utils.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/transition_bcm_fastq_copy.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/__init__.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/emit_workflow_run_state_change.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_workflow_srv.py
Labels: fix, refactor

#522 Fix issue with WRSC generation when a libary record exists
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run_state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/tests/test_create_workflow_run_state.py
Labels: fix

#523 Fix: Metadata Filter && Sortable Endpoint
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/lab.py
Labels: fix

#524 WFM - Extend API capabilities - ongoing workflowrun filter
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_mock_workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
Labels: feature
