Repository umccr/orcabus, pull requests merged in 2024-06, with the labels that each got.

#340 Move from trial project to dev project for umccr-development account
  config/constants.ts
Labels: fix

#338 Updated the sscheck api url from the ssm parameter
  config/constants.ts
  config/stacks/bsRunsUploadManager.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/lambdas/launch_bs_runs_upload_tes/handler.py
  lib/workload/stateless/stacks/bs-runs-upload-manager/lambdas/upload_v2_samplesheet_to_gds_bssh/handler.py
  lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/aws_ssm_helpers.py
  lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/portal_helpers.py
  lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/samplesheet_helpers.py
Labels: feature, fix

#341 Convert api-url to api-domain
  config/constants.ts
  config/stacks/bsRunsUploadManager.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bs-runs-upload-manager/lambdas/upload_v2_samplesheet_to_gds_bssh/handler.py
  lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/portal_helpers.py
  lib/workload/stateless/stacks/bs-runs-upload-manager/layers/src/bs_runs_upload_manager_tools/utils/samplesheet_helpers.py
Labels: fix

#342 fix generate-db-uuid params issue
  lib/workload/stateless/stacks/bclconvert-manager/translator_service/icav2_event_translator.py
Labels: bug, fix

#343 Fixed WorkflowManager allow WRSC Payload nullable
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
Labels: fix

#345 User reference will always start with 'umccr__automated__workflowName`
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/index.ts
Labels: change request, fix

#346 refactor: filemanager ingest
  lib/workload/stateless/stacks/filemanager/database/migrations/0002_add_s3_object_table.sql
  lib/workload/stateless/stacks/filemanager/database/migrations/0003_add_is_delete_marker.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_deleted_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
  lib/workload/stateless/stacks/filemanager/filemanager/README.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/tests/inventory/main.rs
Labels: refactor, filemanager

#348 Updated BasespaceRunsUploadManager event rule with SequenceRunManager convention
  lib/workload/stateless/stacks/bs-runs-upload-manager/Readme.md
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
Labels: change request

#347 Updated SequenceRunManager with latest convention change request
  lib/workload/stateless/stacks/bs-runs-upload-manager/Readme.md
  lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts
  lib/workload/stateless/stacks/sequence-run-manager/Makefile
  lib/workload/stateless/stacks/sequence-run-manager/README.md
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/migrations/0002_alter_sequence_status.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/tests/test_models.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_sequence_srv.py
Labels: change request

#351 Added FileManager EventSource with ICAv2 BYOB pipeline cache buckets
  config/constants.ts
  config/stacks/shared.ts
  lib/workload/stateful/stacks/shared/constructs/event-source/index.ts
Labels: feature

#350 Use hyphens over underscores when generating icav2 paths
  config/constants.ts
  lib/workload/components/event-workflowrunstatechange-internal-to-inputmaker-sfn/lambdas/generate_workflow_run_name_py/generate_workflow_run_name.py
  lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/scripts/trigger_bclconvert_interop_qc.sh
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/lambdas/query_bclconvert_outputs_handler_py/query_bclconvert_outputs_handler.py
Labels: feature, fix

#355 fix(filemanager): make `HeadObject` optional
  config/constants.ts
  config/stacks/fileManager.ts
  lib/workload/components/named-lambda-role/index.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  test/stateless/deployment.test.ts
Labels: fix

#360 Upgraded yarn v4 and bumped dependencies
  .eslintignore
  .eslintrc.json
  .pre-commit-config.yaml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-outdated.cjs
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/releases/yarn-3.5.1.cjs
  .yarn/releases/yarn-4.3.0.cjs
  .yarnrc.yml
  README.md
  eslint.config.mjs
  lib/workload/stateless/stacks/postgres-manager/.yarnrc.yml
  lib/workload/stateless/stacks/postgres-manager/package.json
  lib/workload/stateless/stacks/postgres-manager/yarn.lock
  package.json
  shared/mock-aws.yml
  shared/mock-db.yml
  shared/mock-ica.yml
  yarn.lock
Labels: dependencies

#364 Remove wrongly commented clean target
  Makefile
Labels: fix

#365 Custom Domain for Microservice
  config/config.ts
  config/stacks/fileManager.ts
  config/stacks/metadataManager.ts
  config/stacks/sequenceRunManager.ts
  config/stacks/workflowRunManager.ts
  lib/workload/components/api-gateway/index.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  skel/django-api/deploy/stack.ts
Labels: feature, metadata_manager

#368 Fixed BclConvertManager runtime requirement config
  lib/workload/stateless/stacks/bclconvert-manager/deploy/stack.ts
Labels: fix

#370 Fixed ICAv2 event handle StepFunction Payload schema
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/step_functions_templates/icav2_get_workflow_status_and_raise_internal_event.asl.json
  lib/workload/components/dynamodb-icav2-ready-event-handler-sfn/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json
Labels: fix

#371 Fixed ICAv2 event rule prefix matching
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/index.ts
Labels: fix

#369 Fixed ctTSOv2 workflowVersion to 2.5.0
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/super/constructs/part_1/fastq-list-rows-to-cttsov2-input-maker/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/super/constructs/part_2/cttsov2-input-maker/index.ts
Labels: fix

#367 Fixed WorkflowManager WRSC event processing to handle optional Payload
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/index.ts
  lib/workload/components/dynamodb-icav2-handle-event-change-sfn/step_functions_templates/icav2_get_workflow_status_and_raise_internal_event.asl.json
  lib/workload/components/dynamodb-icav2-ready-event-handler-sfn/step_functions_templates/icav2_launch_workflow_and_raise_internal_event.asl.json
  lib/workload/stateless/stacks/bclconvert-manager/deploy/stack.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/super/constructs/part_1/fastq-list-rows-to-cttsov2-input-maker/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/super/constructs/part_2/cttsov2-input-maker/index.ts
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/lambdas/handle_service_wrsc_event.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager_proc/services/create_workflow_run.py
Labels: fix

#379 Fixed Token Service JWT validation logic
  lib/workload/stateful/stacks/token-service/token_service/rotate_service_jwt.py
Labels: fix

#357 feat: filemanager sea-orm entities
  .github/workflows/prbuild.yml
  lib/pipeline/statelessPipelineStack.ts
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/build.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-build/README.md
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_entities.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/lib.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/build.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
Labels: feature, filemanager

#374 Use instrument run id instead of run id for bclconvert interop qc pipeline
  config/constants.ts
  lib/workload/components/dynamodb-icav2-ready-event-handler-sfn/Readme.md
  lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/Readme.md
  lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/scripts/trigger_bclconvert_interop_qc.sh
  lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager/step_functions_templates/set_bclconvert_interop_qc_cwl_inputs_sfn.asl.json
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/Readme.md
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/selleys/constructs/part_3/bclconvert-interopqc-input-maker/step_function_templates/generate_interopqc_event_maker.asl.json
Labels: feature

#382 Promotion for `postgres-manager` to the stateful stack group (from stateless)
  .github/workflows/prbuild.yml
  Makefile
  config/config.ts
  config/stacks/postgresManager.ts
  eslint.config.mjs
  lib/pipeline/statefulPipelineStack.ts
  lib/pipeline/statelessPipelineStack.ts
  lib/workload/stateful/stacks/postgres-manager/.gitignore
  lib/workload/stateful/stacks/postgres-manager/.yarnrc.yml
  lib/workload/stateful/stacks/postgres-manager/Makefile
  lib/workload/stateful/stacks/postgres-manager/README.md
  lib/workload/stateful/stacks/postgres-manager/compose.yml
  lib/workload/stateful/stacks/postgres-manager/deploy/lambda-build.Dockerfile
  lib/workload/stateful/stacks/postgres-manager/deploy/stack.ts
  lib/workload/stateful/stacks/postgres-manager/function/index.ts
  lib/workload/stateful/stacks/postgres-manager/function/psql-commands.ts
  lib/workload/stateful/stacks/postgres-manager/function/type.ts
  lib/workload/stateful/stacks/postgres-manager/function/utils.ts
  lib/workload/stateful/stacks/postgres-manager/jest.config.js
  lib/workload/stateful/stacks/postgres-manager/package.json
  lib/workload/stateful/stacks/postgres-manager/tests/index.test.ts
  lib/workload/stateful/stacks/postgres-manager/yarn.lock
  lib/workload/stateful/stacks/shared/README.md
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
  skel/django-api/deploy/stack.ts
  test/stateful/pipeline/deployment.test.ts
  test/stateless/deployment.test.ts
  tsconfig.json
Labels: refactor
