Repository umccr/orcabus, pull requests merged in 2025-02, with the labels that each got.

#827 fix(filemanager): enable non-strict querystring parsing
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
Labels: fix, filemanager

#830 Feat(authorization): Add curators group permissions
  lib/workload/stateful/stacks/authorization-manager/README.md
  lib/workload/stateful/stacks/authorization-manager/cedarSchema.json
  lib/workload/stateful/stacks/authorization-manager/http-lambda-authorizer/http_authorizer.py
  lib/workload/stateful/stacks/authorization-manager/stack.ts
Labels: feature

#839 refactor srm srv for detail states and comment
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/domain/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/bssh_event.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_state_srv.py
Labels: feature, fix

#847 deprecated available for ready runs
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
Labels: change request, fix

#843 SRM add time range filter and stats count api
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/comment.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/state.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sequence_run_stats.py
Labels: feature, fix

#851 feat: filemanager storage class
  config/stacks/shared.ts
  lib/workload/stateless/stacks/filemanager/database/migrations/0004_s3_reason.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_created_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_deleted_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/insert_s3_objects.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_created.sql
  lib/workload/stateless/stacks/filemanager/database/queries/ingester/aws/update_reordered_for_deleted.sql
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_entities.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_object.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/sea_orm_active_enums.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
Labels: feature, filemanager

#859 feat: filemanager crawl
  lib/workload/stateless/stacks/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/Dockerfile
  lib/workload/stateless/stacks/filemanager/database/migrations/0005_s3_crawl.sql
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-build/src/gen_openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/sqs.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/prelude.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/s3_crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/entities/sea_orm_active_enums.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/message.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/filter/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/header.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
Labels: feature, filemanager

#863 Feat(MM): Expand Metadata List Filtering
  lib/workload/stateless/stacks/metadata-manager/app/serializers/library.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/subject.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/library.py
  lib/workload/stateless/stacks/metadata-manager/app/viewsets/subject.py
Labels: feature

#862 feat: filemanager long-lived presigned URLs
  config/config.ts
  config/constants.ts
  config/stacks/accessKeySecret.ts
  config/stacks/fileManager.ts
  lib/workload/stateful/stacks/access-key-secret/README.md
  lib/workload/stateful/stacks/access-key-secret/index.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/inventory.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/config.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/secrets_manager.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/credentials.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
  test/stateful/access-key-user/accessKeyUser.test.ts
  test/stateful/pipeline/deployment.test.ts
  test/stateless/deployment.test.ts
Labels: feature, filemanager

#867 feat(htsget): update htsget stack
  config/stacks/htsget.ts
  lib/workload/stateless/stacks/htsget/deploy.toml
  lib/workload/stateless/stacks/htsget/stack.ts
  package.json
  yarn.lock
Labels: fix, filemanager

#868 Feat(MM): Dedup `topup` / `rerun` Libraries && Cleanup Script
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/clean_duplicated_libraries.py
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-django-command/index.ts
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-django-command/lambda.Dockerfile
  lib/workload/stateless/stacks/metadata-manager/deploy/stack.ts
  lib/workload/stateless/stacks/metadata-manager/handler/django_command.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/utils.py
  lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py
Labels: change request

#878 Fix/srm duplicate events
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/bssh_event.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_sequence_domain.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_sequence_srv.py
Labels: fix

#882 feat(filemanager): allow updating ingest id even if already set
  lib/workload/stateless/stacks/filemanager/docs/API_GUIDE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/update.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: feature, filemanager
