Repository umccr/orcabus, pull requests merged in 2025-03, with the labels that each got.

#876 Feat/srm runs detail and librarylinking
  config/stacks/sequenceRunManager.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/fields.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/migrations/0005_sequence_experiment_name_libraryassociation.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/__init__.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/tests/factories.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/tests/test_models.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/tests/test_viewsets.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sequence_run_action.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/bssh_event.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/bssh_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_library_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_state_srv.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/case.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_bssh_event.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/tests/test_sequence_srv.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
Labels: feature, migration

#886 Feat (SRM) add failed events slack notification
  config/stacks/sequenceRunManager.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
Labels: feature

#887 Fix (SRM) quick fix of the orcaUI base url
  config/stacks/sequenceRunManager.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
Labels: fix

#855 Added in bssh tools layer
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/__init__.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/poetry.lock
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/pyproject.toml
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/__init__.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/aws_ssm_helpers.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/compression_helpers.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/directory_helper.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/globals.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/icav2_analysis_helpers.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/logger.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/run_info_helpers.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/sample_helper.py
  lib/workload/components/python-bssh-tools-layer/bssh_manager_tools/src/utils/samplesheet_helper.py
  lib/workload/components/python-bssh-tools-layer/index.ts
Labels: feature

#892 fix bssh tools layer name conflict
  lib/workload/components/python-bssh-tools-layer/index.ts
Labels: fix

#917 fix: avoid cross compiling on same architecture
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/function.ts
Labels: fix, filemanager

#889 Library and Samplesheet Linking for Existing Sequence Runs
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sample_sheet.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/check_and_create_library_linking.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/lambdas/check_and_create_samplesheet.py
  test/stateless/deployment.test.ts
Labels: feature

#920 feat(filemanager): ignore directories
  config/stacks/shared.ts
  lib/pipeline/statelessPipelineStack.ts
  lib/workload/stateful/stacks/shared/constructs/event-source/index.ts
  package.json
  test/stateful/shared/eventSourceConstruct.test.ts
  yarn.lock
Labels: feature, filemanager

#937 Fix: Failing dependency check
  package.json
  yarn.lock
Labels: dependencies

#940 Fix duplicate results from multiple library_ids filter
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py
Labels: bug
