Repository umccr/orcabus, pull requests merged in 2025-05, with the labels that each got.

#981 fix(filemanager): ignore transient secret errors
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/secrets_manager.rs
Labels: fix

#977 Added project montauk and external project buckets object
  config/constants.ts
  config/stacks/fileManager.ts
  config/stacks/shared.ts
Labels: filemanager

#983 Added data-sharing manager and toolkit
  lib/workload/stateless/stacks/data-sharing-manager/Readme.md
  lib/workload/stateless/stacks/data-sharing-manager/scripts/data-sharing-tool.py
  lib/workload/stateless/stacks/data-sharing-manager/scripts/install.sh
Labels: documentation, feature

#985 Updated athena docs on data sharing tool
  lib/workload/stateless/stacks/data-sharing-manager/Readme.md
  lib/workload/stateless/stacks/data-sharing-manager/scripts/data-sharing-tool.py
  lib/workload/stateless/stacks/data-sharing-manager/scripts/install.sh
Labels: documentation

#993 Fastq glue should listen to SRM succeeded events
  config/constants.ts
  config/stacks/fastqGlue.ts
  lib/workload/components/python-fastq-tools-layer/fastq_tools_layer/src/fastq_tools/__init__.py
  lib/workload/components/python-fastq-tools-layer/fastq_tools_layer/src/fastq_tools/utils/create_helpers.py
  lib/workload/components/python-fastq-tools-layer/fastq_tools_layer/src/fastq_tools/utils/models.py
  lib/workload/components/python-fastq-tools-layer/fastq_tools_layer/src/fastq_tools/utils/query_helpers.py
  lib/workload/components/python-sequence-tools-layer/index.ts
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/poetry.lock
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/pyproject.toml
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/__init__.py
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/utils/__init__.py
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/utils/aws_helpers.py
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/utils/globals.py
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/utils/models.py
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/utils/requests_helpers.py
  lib/workload/components/python-sequence-tools-layer/sequence_tools_layer/src/sequence_tools/utils/sequence_helpers.py
  lib/workload/stateless/stacks/fastq-glue/deploy/index.ts
  lib/workload/stateless/stacks/fastq-glue/deploy/interfaces.ts
  lib/workload/stateless/stacks/fastq-glue/lambdas/add_read_sets_to_fastq_objects_py/add_read_sets_to_fastq_objects.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/create_fastq_set_object_py/create_fastq_set_object.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_bclconvert_data_from_samplesheet_py/get_bclconvert_data_from_samplesheet.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_bclconvert_data_from_samplesheet_py/requirements.txt
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_fastq_objects_py/get_fastq_objects.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_file_names_from_fastq_list_csv_py/get_file_names_from_fastq_list_csv.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_library_id_list_from_samplesheet_py/get_library_id_list_from_samplesheet.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_sample_demultiplex_stats_py/get_sample_demultiplex_stats.py
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_samples_from_samplesheet_py/requirements.txt
  lib/workload/stateless/stacks/fastq-glue/step_functions_templates/fastq_set_add_read_set_template_sfn.asl.json
  lib/workload/stateless/stacks/fastq-glue/step_functions_templates/fastq_set_generation_template_sfn.asl.json
Labels: change request

#990 fix(filemanager): order nulls last desc and first asc to preserve correct current state
  lib/workload/stateless/stacks/filemanager/database/queries/api/reset_current_state.sql
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/queries/list.rs
Labels: fix, filemanager

#995 Fastq glue should listen to SRM succeeded events
  lib/workload/stateless/stacks/fastq-glue/deploy/index.ts
  lib/workload/stateless/stacks/fastq-glue/deploy/interfaces.ts
  lib/workload/stateless/stacks/fastq-glue/lambdas/get_sample_demultiplex_stats_py/get_sample_demultiplex_stats.py
  lib/workload/stateless/stacks/fastq-glue/step_functions_templates/fastq_set_add_read_set_template_sfn.asl.json
Labels: bug

#996 Dont push s3 details for event
  lib/workload/stateless/stacks/fastq-manager/app/api/fastq_manager_api_tools/api/v1/routers/fastq_set.py
Labels: bug

#997 refactor(stateless): detach direct dependency on the filemanager stack
  config/constants.ts
  config/stacks/fileManager.ts
  config/stacks/fmAnnotator.ts
  config/stacks/htsget.ts
  lib/workload/components/api-gateway/index.ts
  lib/workload/stateless/stacks/fmannotator/deploy/stack.ts
  lib/workload/stateless/stacks/htsget/stack.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
  package.json
  yarn.lock
Labels: platform, refactor

#1000 refactor(platform): remove filemanager stack
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: refactor, filemanager

#1002 refactor(platform): remove access key secret stack
  lib/workload/stateful/statefulStackCollectionClass.ts
Labels: platform, refactor
