Repository umccr/orcabus, pull requests merged in 2025-06, with the labels that each got.

#1003 sample source is not required for data sharing model
  lib/workload/stateless/stacks/data-sharing-manager/ecs/tasks/generate_data_summary_report/data_summary_reporting_tools/src/data_summary_reporting_tools/models.py
Labels: bug

#980 add srllc and srssc events
  config/stacks/schema/events.ts
  docs/schemas/events/sequencerunmanager/Makefile
  docs/schemas/events/sequencerunmanager/SequenceRunLibraryLinkingChange.schema.json
  docs/schemas/events/sequencerunmanager/SequenceRunSampleSheetChange.schema.json
  docs/schemas/events/sequencerunmanager/example/SRLLC.json
  docs/schemas/events/sequencerunmanager/example/SRSSC.json
Labels: feature

#1001 Added v3 indexes to cttsov2 samplesheet maker
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_3/fastq-list-row-event-shower-complete-to-cttsov2-ready/lambdas/build_cttsov2_samplesheet_py/build_cttso_v2_samplesheet.py
Labels: fix

#1004 Unquote next link, otherwise filemanager doesnt process it
  lib/workload/components/python-filemanager-tools-layer/filemanager_tools_layer/src/filemanager_tools/utils/request_helpers.py
Labels: fix

#1006 Detach icav2 data copy manager stack
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#1008 Detach primary data services
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_1/initialise-wts-and-wgs-libraries/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/handy-pal/part_2/populate-fastq-list-rows/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_1/initialise-cttsov2-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_2/populate-fastq-list-row-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/jb-weld/part_3/fastq-list-row-event-shower-complete-to-cttsov2-ready/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_1/initialise-wgts-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_2/populate-fastq-list-row-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_3/fastq-list-rows-shower-complete-to-wgts-qc/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_4/push-fastq-list-row-qc-complete-event/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/kwik/part_5/library-qc-complete-event/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_1/initialise-tn-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/loctite/part_2/update-fastq-list-rows-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_1/initialise-wts-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/mod-podge/part_2/update-fastq-list-rows-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/nails/part_1/initialise-library-db/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/pva/part_1/initialise-umccrise-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/roket/part_1/initialise-rnasum-library-dbs/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/index.ts
  lib/workload/stateless/stacks/stacky-mcstackface/glue-constructs/t-rex/part_1/initialise-wts-wgs-libraries/index.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: refactor

#1010 feat(mm): Update metadata user to rds-iam
  config/stacks/postgresManager.ts
Labels: refactor

#1021 Chore: Migrate Stateful Stack
  lib/workload/stateful/statefulStackCollectionClass.ts
Labels: refactor

#1024 Add ecs managed policy for fargate tasks
  lib/workload/stateless/stacks/fastq-manager/app/api/fastq_manager_api_tools/api/v1/routers/fastq_set.py
  lib/workload/stateless/stacks/fastq-manager/deploy/stack.ts
Labels: fix

#1032 Custom retry omitted by AWS Sfn Workflow Studio
  lib/workload/stateless/stacks/data-sharing-manager/step_functions_templates/packaging_sfn_template.asl.json
Labels: bug

#1035 Correctly collect requirements after unarchiving
  lib/workload/stateless/stacks/fastq-sync/step_functions_templates/fastq_set_updated.asl.json
Labels: bug
