Repository umccr/orcabus, pull requests merged in 2025-04, with the labels that each got.

#941 Enable corepack before all yarn --install commands
  .gitpod.yml
  Makefile
  lib/pipeline/statefulPipelineStack.ts
  lib/pipeline/statelessPipelineStack.ts
  lib/workload/stateful/stacks/postgres-manager/Makefile
Labels: bug

#944 bump: cdk from 2.186.0 to 2.187.0
  package.json
  yarn.lock
Labels: dependencies

#943 Fix - (SRM) ignore status changed after sequece run succeed
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager_proc/services/sequence_srv.py
Labels: bug

#930 feat: use separate role for filemanager API function
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature, filemanager

#931 fix(filemanager): pagination of nested links
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/env.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/header.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: fix, filemanager

#928 fix: filemanager secret cache
  lib/workload/stateless/stacks/filemanager/Cargo.lock
  lib/workload/stateless/stacks/filemanager/filemanager-api-lambda/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/Cargo.toml
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/secrets_manager.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/get.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/ingest.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/list.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/pagination.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/presign.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/update.rs
Labels: fix, filemanager

#932 Fix(SSCheck): Rollback v2 samplesheet tso500l data entry
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/globals.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/v2_samplesheet_builder.py
Labels: fix

#952 Fix(sscheck): Strip topup in library_id
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/samplesheet.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/v2_samplesheet_builder.py
Labels: fix

#927 upgrade orcabus to postgres 16
  config/stacks/shared.ts
  lib/workload/stateful/stacks/shared/constructs/database/index.ts
  lib/workload/stateless/stacks/filemanager/database/Dockerfile
  lib/workload/stateless/stacks/metadata-manager/Makefile
  shared/mock-db.yml
Labels: platform, fix

#956 bump: cdk from 2.187.0 to 2.189.0
  package.json
  yarn.lock
Labels: dependencies

#958 Fix #957
  lib/workload/stateless/stacks/bclconvert-manager/deploy/stack.ts
Labels: fix

#955 fix: filemanager sequencer ordering
  lib/workload/stateless/stacks/filemanager/database/queries/api/select_existing_by_bucket_key.sql
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/api.ts
  lib/workload/stateless/stacks/filemanager/deploy/constructs/functions/ingest.ts
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/docs/ARCHITECTURE.md
  lib/workload/stateless/stacks/filemanager/filemanager/src/clients/aws/s3.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/ingester_paired.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/aws/query.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/database/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/collecter.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/crawl.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/inventory.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/events/aws/mod.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/handlers/aws.rs
Labels: fix, filemanager

#898 Add fastq unarchiving service
  config/config.ts
  config/constants.ts
  config/stacks/fastqUnarchivingManager.ts
  lib/workload/stateful/stacks/fastq-unarchiving-dynamodb/Readme.md
  lib/workload/stateful/stacks/fastq-unarchiving-dynamodb/deploy/index.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/fastq-unarchiving/Readme.md
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/__init__.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/api/__init__.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/api/v1/__init__.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/api/v1/job.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/events/__init__.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/events/events.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/globals.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/models/__init__.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/models/job.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/models/query.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/fastq_unarchiving_api/utils.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/handler.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/interface/requirements.txt
  lib/workload/stateless/stacks/fastq-unarchiving/app/lambdas/create_csv_for_s3_steps_copy_lambda_py/create_csv_for_s3_steps_copy_lambda.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/lambdas/create_csv_for_s3_steps_copy_lambda_py/requirements.txt
  lib/workload/stateless/stacks/fastq-unarchiving/app/lambdas/find_original_ingest_id_py/find_original_ingest_id.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/lambdas/split_fastq_ids_by_instrument_run_id_lambda_py/split_fastq_ids_by_instrument_run_id_lambda.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/lambdas/update_ingest_id_py/update_ingest_id.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/lambdas/update_job_database_py/update_job_database.py
  lib/workload/stateless/stacks/fastq-unarchiving/app/step_functions_templates/run_s3_steps_copy_sfns_sfn_template.asl.json
  lib/workload/stateless/stacks/fastq-unarchiving/deploy/index.ts
  lib/workload/stateless/stacks/fastq-unarchiving/deploy/interfaces.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#788 Initialise ICAv2 Data Copy Manager
  config/config.ts
  config/constants.ts
  config/stacks/icav2DataCopyManager.ts
  lib/workload/stateful/stacks/icav2-data-copy-manager-dynamo-db/deploy/index.ts
  lib/workload/stateful/statefulStackCollectionClass.ts
  lib/workload/stateless/stacks/icav2-data-copy-manager/Readme.md
  lib/workload/stateless/stacks/icav2-data-copy-manager/deploy/index.ts
  lib/workload/stateless/stacks/icav2-data-copy-manager/deploy/interfaces.ts
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/find_single_part_files_py/find_single_part_files.py
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/find_single_part_files_py/requirements.txt
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/generate_copy_job_list_py/generate_copy_job_list.py
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/generate_copy_job_list_py/requirements.txt
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/launch_icav2_copy_py/launch_icav2_copy.py
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/launch_icav2_copy_py/requirements.txt
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/upload_single_part_file_py/requirements.txt
  lib/workload/stateless/stacks/icav2-data-copy-manager/lambdas/upload_single_part_file_py/upload_single_part_file.py
  lib/workload/stateless/stacks/icav2-data-copy-manager/step_functions_templates/handle_copy_jobs.asl.json
  lib/workload/stateless/stacks/icav2-data-copy-manager/step_functions_templates/save_job_and_internal_task_token_in_db.asl.json
  lib/workload/stateless/stacks/icav2-data-copy-manager/step_functions_templates/send_internal_task_token.asl.json
  lib/workload/stateless/statelessStackCollectionClass.ts
Labels: feature

#966 Fix ora inputs sfn for cttso workflow input handler
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json
Labels: bug

#965 Updated bssh fastq copy manager
  config/stacks/bsshIcav2FastqCopyManager.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/constructs/bssh-icav2-fastq-copy-manager/index.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/interfaces.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/deploy/stack.ts
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/lambdas/query_bclconvert_outputs_handler_py/Dockerfile
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/lambdas/query_bclconvert_outputs_handler_py/query_bclconvert_outputs_handler.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/layers/src/bssh_manager_tools/utils/manifest_helper.py
  lib/workload/stateless/stacks/bssh-icav2-fastq-copy-manager/step_functions_templates/bclconvert_success_event_state_machine.json
Labels: feature, fix
