Repository umccr/orcabus, pull requests merged in 2025-01, with the labels that each got.

#797 Feat: Django Deployable Swagger
  lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
  lib/workload/stateless/stacks/metadata-manager/app/settings/local.py
  lib/workload/stateless/stacks/metadata-manager/app/urls/base.py
  lib/workload/stateless/stacks/metadata-manager/app/urls/local.py
  lib/workload/stateless/stacks/metadata-manager/deploy/construct/lambda-api/index.ts
  lib/workload/stateless/stacks/sequence-run-manager/deploy/stack.ts
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/local.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/urls/local.py
  lib/workload/stateless/stacks/workflow-manager/deploy/stack.ts
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/local.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/urls/local.py
  skel/django-api/deploy/stack.ts
  skel/django-api/project_name/settings/base.py
  skel/django-api/project_name/settings/local.py
Labels: feature, platform

#796 Fix cttso input maker sfn
  lib/workload/stateless/stacks/cttso-v2-pipeline-manager/step_functions_templates/set_cttso_v2_nf_inputs.asl.json
Labels: bug, fix

#799 fix(WFM): Put Back `camelCase` Serializer
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py
Labels: fix

#801 fix(filemanager): pin htsget-rs version inside the htsget stack
  lib/workload/stateless/stacks/htsget/stack.ts
  package.json
  yarn.lock
Labels: fix

#800 Fix(WFM): Portal Run Id Creation
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/management/commands/generate_analysis_for_metadata.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/models/utils.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/tests/test_models.py
Labels: fix

#803 feat(filemanager): deployable swagger ui
  lib/workload/stateless/stacks/filemanager/deploy/stack.ts
  lib/workload/stateless/stacks/filemanager/filemanager-api-server/src/main.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/error.rs
  lib/workload/stateless/stacks/filemanager/filemanager/src/routes/openapi.rs
Labels: feature, filemanager

#805 build: update htsget-lambda dependency
  package.json
  yarn.lock
Labels: fix, filemanager

#806 Feat(mm): add `override_cycles` to the Library
  lib/workload/stateless/stacks/metadata-manager/README.md
  lib/workload/stateless/stacks/metadata-manager/app/management/commands/insert_mock_data.py
  lib/workload/stateless/stacks/metadata-manager/app/migrations/0004_historicallibrary_override_cycles_and_more.py
  lib/workload/stateless/stacks/metadata-manager/app/models/library.py
  lib/workload/stateless/stacks/metadata-manager/app/tests/factories.py
  lib/workload/stateless/stacks/metadata-manager/docs/schema.drawio.svg
  lib/workload/stateless/stacks/metadata-manager/proc/service/load_csv_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/service/tracking_sheet_srv.py
  lib/workload/stateless/stacks/metadata-manager/proc/tests/test_tracking_sheet_srv.py
Labels: feature, metadata_manager

#808 feat(sscheck): Add New SSCheck Stack
  Makefile
  config/config.ts
  config/stacks/sampleSheetChecker.ts
  lib/workload/stateless/stacks/sample-sheet-check/Makefile
  lib/workload/stateless/stacks/sample-sheet-check/README.md
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/.gitignore
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/Makefile
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/README.md
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/handler.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/lambda.Dockerfile
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/main.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/requirements.txt
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/__init__.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/checker.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/errors.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/globals.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/http.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/logger.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/metadata.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/samplesheet.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/v2_samplesheet_builder.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/tests/sample/mock-1.csv
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/tests/sample/mock-2.csv
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/tests/test_sample_sheet.py
  lib/workload/stateless/stacks/sample-sheet-check/stack.ts
  lib/workload/stateless/statelessStackCollectionClass.ts
  test/stateless/deployment.test.ts
Labels: feature, pipeline

#810 fix(sscheck): change metadata reference domain name
  config/stacks/sampleSheetChecker.ts
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/metadata.py
  lib/workload/stateless/stacks/sample-sheet-check/stack.ts
Labels: fix

#813 fix(token-service): generated password should contain required characters
  lib/workload/stateful/stacks/token-service/token_service/cognitor/__init__.py
  lib/workload/stateful/stacks/token-service/token_service/cognitor/tests.py
  lib/workload/stateful/stacks/token-service/token_service/rotate_service_jwt.py
  lib/workload/stateful/stacks/token-service/token_service/rotate_service_user.py
Labels: platform, fix

#817 Chore(sscheck): Re-enable logging and detailed error message
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/handler.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/checker.py
  lib/workload/stateless/stacks/sample-sheet-check/sample-sheet-check-lambda/src/logger.py
  lib/workload/stateless/stacks/sample-sheet-check/stack.ts
Labels: refactor

#820 refactor srm relation orcabus id
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/migrations/0004_alter_comment_association_id.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/models/comment.py
Labels: change request

#821 add lookup_value_regex to allow special char in url
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/comment.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_comment.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/viewsets/workflow_run_stats.py
Labels: bug, fix

#823 Fix: `orcabus_id` marked required in OpenAPI schema response
  lib/workload/stateless/stacks/metadata-manager/app/fields.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/contact.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/individual.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/library.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/project.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/sample.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/subject.py
  lib/workload/stateless/stacks/metadata-manager/app/serializers/utils.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/fields.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/comment.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/sequence.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/serializers/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/fields.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_context.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/analysis_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/library.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/payload.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/state.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/serializers/workflow_run_comment.py
Labels: fix

#814 fix(pipeline): enable logging on github action runner
  lib/pipeline/statelessPipelineStack.ts
Labels: fix, pipeline

#824 Feat: Test Deployed OpenAPI Schema with Typescript Type Check
  lib/pipeline/component/uiOpenAPITest.ts
  lib/pipeline/statelessPipelineStack.ts
  lib/workload/stateless/stacks/metadata-manager/app/settings/base.py
  lib/workload/stateless/stacks/sequence-run-manager/sequence_run_manager/settings/base.py
  lib/workload/stateless/stacks/workflow-manager/workflow_manager/settings/base.py
Labels: feature

#835 Fix(testing): OrcaUI Type Check
  lib/pipeline/component/uiOpenAPITest.ts
Labels: fix

#840 fix(pg-dd): remove double compression
  lib/workload/stateless/stacks/pg-dd/pg_dd/pg_dd.py
  lib/workload/stateless/stacks/pg-dd/poetry.lock
Labels: platform, fix

#842 Fix: OrcaUI Type Testing
  lib/pipeline/component/uiOpenAPITest.ts
Labels: fix
